#include "fitFile.idl"
#include "fitMesgNum.idl"
#include "fitChecksum.idl"
#include "fitFileFlags.idl"
#include "fitMesgCount.idl"
#include "fitDateTime.idl"
#include "fitLocalDateTime.idl"
#include "fitMessageIndex.idl"
#include "fitDeviceIndex.idl"
#include "fitGender.idl"
#include "fitLanguage.idl"
#include "fitLanguageBits0.idl"
#include "fitLanguageBits1.idl"
#include "fitLanguageBits2.idl"
#include "fitLanguageBits3.idl"
#include "fitLanguageBits4.idl"
#include "fitTimeZone.idl"
#include "fitDisplayMeasure.idl"
#include "fitDisplayHeart.idl"
#include "fitDisplayPower.idl"
#include "fitDisplayPosition.idl"
#include "fitSwitch.idl"
#include "fitSport.idl"
#include "fitSportBits0.idl"
#include "fitSportBits1.idl"
#include "fitSportBits2.idl"
#include "fitSportBits3.idl"
#include "fitSportBits4.idl"
#include "fitSportBits5.idl"
#include "fitSportBits6.idl"
#include "fitSubSport.idl"
#include "fitSportEvent.idl"
#include "fitActivity.idl"
#include "fitIntensity.idl"
#include "fitSessionTrigger.idl"
#include "fitAutolapTrigger.idl"
#include "fitLapTrigger.idl"
#include "fitTimeMode.idl"
#include "fitBacklightMode.idl"
#include "fitDateMode.idl"
#include "fitBacklightTimeout.idl"
#include "fitEvent.idl"
#include "fitEventType.idl"
#include "fitTimerTrigger.idl"
#include "fitFitnessEquipmentState.idl"
#include "fitTone.idl"
#include "fitAutoscroll.idl"
#include "fitActivityClass.idl"
#include "fitHrZoneCalc.idl"
#include "fitPwrZoneCalc.idl"
#include "fitWktStepDuration.idl"
#include "fitWktStepTarget.idl"
#include "fitGoal.idl"
#include "fitGoalRecurrence.idl"
#include "fitGoalSource.idl"
#include "fitSchedule.idl"
#include "fitCoursePoint.idl"
#include "fitManufacturer.idl"
#include "fitGarminProduct.idl"
#include "fitAntplusDeviceType.idl"
#include "fitAntNetwork.idl"
#include "fitWorkoutCapabilities.idl"
#include "fitBatteryStatus.idl"
#include "fitHrType.idl"
#include "fitCourseCapabilities.idl"
#include "fitWeight.idl"
#include "fitWorkoutHr.idl"
#include "fitWorkoutPower.idl"
#include "fitBpStatus.idl"
#include "fitUserLocalId.idl"
#include "fitSwimStroke.idl"
#include "fitActivityType.idl"
#include "fitActivitySubtype.idl"
#include "fitActivityLevel.idl"
#include "fitSide.idl"
#include "fitLeftRightBalance.idl"
#include "fitLeftRightBalance100.idl"
#include "fitLengthType.idl"
#include "fitDayOfWeek.idl"
#include "fitConnectivityCapabilities.idl"
#include "fitWeatherReport.idl"
#include "fitWeatherStatus.idl"
#include "fitWeatherSeverity.idl"
#include "fitWeatherSevereType.idl"
#include "fitTimeIntoDay.idl"
#include "fitLocaltimeIntoDay.idl"
#include "fitStrokeType.idl"
#include "fitBodyLocation.idl"
#include "fitSegmentLapStatus.idl"
#include "fitSegmentLeaderboardType.idl"
#include "fitSegmentDeleteStatus.idl"
#include "fitSegmentSelectionType.idl"
#include "fitSourceType.idl"
#include "fitLocalDeviceType.idl"
#include "fitBleDeviceType.idl"
#include "fitAntChannelId.idl"
#include "fitDisplayOrientation.idl"
#include "fitWorkoutEquipment.idl"
#include "fitWatchfaceMode.idl"
#include "fitDigitalWatchfaceLayout.idl"
#include "fitAnalogWatchfaceLayout.idl"
#include "fitRiderPositionType.idl"
#include "fitPowerPhaseType.idl"
#include "fitCameraEventType.idl"
#include "fitSensorType.idl"
#include "fitBikeLightNetworkConfigType.idl"
#include "fitCommTimeoutType.idl"
#include "fitCameraOrientationType.idl"
#include "fitAttitudeStage.idl"
#include "fitAttitudeValidity.idl"
#include "fitAutoSyncFrequency.idl"
#include "fitExdLayout.idl"
#include "fitExdDisplayType.idl"
#include "fitExdDataUnits.idl"
#include "fitExdQualifiers.idl"
#include "fitExdDescriptors.idl"
#include "fitAutoActivityDetect.idl"
#include "fitSupportedExdScreenLayouts.idl"
#include "fitFitBaseType.idl"
#include "fitTurnType.idl"
#include "fitBikeLightBeamAngleMode.idl"
#include "fitFitBaseUnit.idl"
#include "fitSetType.idl"
#include "fitMaxMetCategory.idl"
#include "fitExerciseCategory.idl"
#include "fitBenchPressExerciseName.idl"
#include "fitCalfRaiseExerciseName.idl"
#include "fitCardioExerciseName.idl"
#include "fitCarryExerciseName.idl"
#include "fitChopExerciseName.idl"
#include "fitCoreExerciseName.idl"
#include "fitCrunchExerciseName.idl"
#include "fitCurlExerciseName.idl"
#include "fitDeadliftExerciseName.idl"
#include "fitFlyeExerciseName.idl"
#include "fitHipRaiseExerciseName.idl"
#include "fitHipStabilityExerciseName.idl"
#include "fitHipSwingExerciseName.idl"
#include "fitHyperextensionExerciseName.idl"
#include "fitLateralRaiseExerciseName.idl"
#include "fitLegCurlExerciseName.idl"
#include "fitLegRaiseExerciseName.idl"
#include "fitLungeExerciseName.idl"
#include "fitOlympicLiftExerciseName.idl"
#include "fitPlankExerciseName.idl"
#include "fitPlyoExerciseName.idl"
#include "fitPullUpExerciseName.idl"
#include "fitPushUpExerciseName.idl"
#include "fitRowExerciseName.idl"
#include "fitShoulderPressExerciseName.idl"
#include "fitShoulderStabilityExerciseName.idl"
#include "fitShrugExerciseName.idl"
#include "fitSitUpExerciseName.idl"
#include "fitSquatExerciseName.idl"
#include "fitTotalBodyExerciseName.idl"
#include "fitTricepsExtensionExerciseName.idl"
#include "fitWarmUpExerciseName.idl"
#include "fitRunExerciseName.idl"
#include "fitWaterType.idl"
#include "fitTissueModelType.idl"
#include "fitDiveGasStatus.idl"
#include "fitDiveAlert.idl"
#include "fitDiveAlarmType.idl"
#include "fitDiveBacklightMode.idl"
#include "fitSleepLevel.idl"
#include "fitSpo2MeasurementType.idl"
#include "fitCcrSetpointSwitchMode.idl"
#include "fitDiveGasMode.idl"
#include "fitProjectileType.idl"
#include "fitFaveroProduct.idl"
#include "fitSplitType.idl"
#include "fitClimbProEvent.idl"
#include "fitGasConsumptionRateType.idl"
#include "fitTapSensitivity.idl"
#include "fitRadarThreatLevelType.idl"
#include "fitMaxMetSpeedSource.idl"
#include "fitMaxMetHeartRateSource.idl"
#include "fitHrvStatus.idl"
#include "fitNoFlyTimeMode.idl"
