#include "fitTypeDecls.idl"
#include "fitAllTypes.idl"

struct<"AadAccelFeatures", ""> AadAccelFeatures {
	uint32<"Uint32", 253, -1, "", 1, 1, "", "", "", "", "", "", "", ""> @Timestamp;
	uint16<"Uint16", 0, -1, "", 1, 1, "s", "", "", "", "", "Time interval length in seconds", "", ""> @Time;
	uint32<"Uint32", 1, -1, "", 1, 1, "", "", "", "", "", "Total accelerometer energy in the interval", "", ""> @EnergyTotal;
	uint16<"Uint16", 2, -1, "", 1, 1, "", "", "", "", "", "Count of zero crossings", "", ""> @ZeroCrossCnt;
	uint8<"Uint8", 3, -1, "", 1, 1, "", "", "", "", "", "Instance ID of zero crossing algorithm", "", ""> @Instance;
	uint16<"Uint16", 4, -1, "", 25, 1, "s", "", "", "", "", "Total accelerometer time above threshold in the interval", "", ""> @TimeAboveThreshold;
};
