#include "fitFileId.idl"
#include "fitFileCreator.idl"
#include "fitTimestampCorrelation.idl"
#include "fitSoftware.idl"
#include "fitSlaveDevice.idl"
#include "fitCapabilities.idl"
#include "fitFileCapabilities.idl"
#include "fitMesgCapabilities.idl"
#include "fitFieldCapabilities.idl"
#include "fitDeviceSettings.idl"
#include "fitUserProfile.idl"
#include "fitHrmProfile.idl"
#include "fitSdmProfile.idl"
#include "fitBikeProfile.idl"
#include "fitConnectivity.idl"
#include "fitWatchfaceSettings.idl"
#include "fitOhrSettings.idl"
#include "fitTimeInZone.idl"
#include "fitZonesTarget.idl"
#include "fitSport.idl"
#include "fitHrZone.idl"
#include "fitSpeedZone.idl"
#include "fitCadenceZone.idl"
#include "fitPowerZone.idl"
#include "fitMetZone.idl"
#include "fitDiveSettings.idl"
#include "fitDiveAlarm.idl"
#include "fitDiveApneaAlarm.idl"
#include "fitDiveGas.idl"
#include "fitGoal.idl"
#include "fitActivity.idl"
#include "fitSession.idl"
#include "fitLap.idl"
#include "fitLength.idl"
#include "fitRecord.idl"
#include "fitEvent.idl"
#include "fitDeviceInfo.idl"
#include "fitDeviceAuxBatteryInfo.idl"
#include "fitTrainingFile.idl"
#include "fitWeatherConditions.idl"
#include "fitWeatherAlert.idl"
#include "fitGpsMetadata.idl"
#include "fitCameraEvent.idl"
#include "fitGyroscopeData.idl"
#include "fitAccelerometerData.idl"
#include "fitMagnetometerData.idl"
#include "fitBarometerData.idl"
#include "fitThreeDSensorCalibration.idl"
#include "fitOneDSensorCalibration.idl"
#include "fitVideoFrame.idl"
#include "fitObdiiData.idl"
#include "fitNmeaSentence.idl"
#include "fitAviationAttitude.idl"
#include "fitVideo.idl"
#include "fitVideoTitle.idl"
#include "fitVideoDescription.idl"
#include "fitVideoClip.idl"
#include "fitSet.idl"
#include "fitJump.idl"
#include "fitSplit.idl"
#include "fitSplitSummary.idl"
#include "fitClimbPro.idl"
#include "fitFieldDescription.idl"
#include "fitDeveloperDataId.idl"
#include "fitCourse.idl"
#include "fitCoursePoint.idl"
#include "fitSegmentId.idl"
#include "fitSegmentLeaderboardEntry.idl"
#include "fitSegmentPoint.idl"
#include "fitSegmentLap.idl"
#include "fitSegmentFile.idl"
#include "fitWorkout.idl"
#include "fitWorkoutSession.idl"
#include "fitWorkoutStep.idl"
#include "fitExerciseTitle.idl"
#include "fitSchedule.idl"
#include "fitTotals.idl"
#include "fitWeightScale.idl"
#include "fitBloodPressure.idl"
#include "fitMonitoringInfo.idl"
#include "fitMonitoring.idl"
#include "fitMonitoringHrData.idl"
#include "fitSpo2Data.idl"
#include "fitHr.idl"
#include "fitStressLevel.idl"
#include "fitMaxMetData.idl"
#include "fitHsaBodyBatteryData.idl"
#include "fitHsaEvent.idl"
#include "fitHsaAccelerometerData.idl"
#include "fitHsaGyroscopeData.idl"
#include "fitHsaStepData.idl"
#include "fitHsaSpo2Data.idl"
#include "fitHsaStressData.idl"
#include "fitHsaRespirationData.idl"
#include "fitHsaHeartRateData.idl"
#include "fitHsaConfigurationData.idl"
#include "fitHsaWristTemperatureData.idl"
#include "fitMemoGlob.idl"
#include "fitSleepLevel.idl"
#include "fitAntChannelId.idl"
#include "fitAntRx.idl"
#include "fitAntTx.idl"
#include "fitExdScreenConfiguration.idl"
#include "fitExdDataFieldConfiguration.idl"
#include "fitExdDataConceptConfiguration.idl"
#include "fitDiveSummary.idl"
#include "fitAadAccelFeatures.idl"
#include "fitHrv.idl"
#include "fitBeatIntervals.idl"
#include "fitHrvStatusSummary.idl"
#include "fitHrvValue.idl"
#include "fitRawBbi.idl"
#include "fitRespirationRate.idl"
#include "fitChronoShotSession.idl"
#include "fitChronoShotData.idl"
#include "fitTankUpdate.idl"
#include "fitTankSummary.idl"
#include "fitSleepAssessment.idl"
#include "fitSkinTempOvernight.idl"
