#include "fitTypeDecls.idl"
#include "fitAllTypes.idl"

struct<"BeatIntervals", ""> BeatIntervals {
	uint32<"Uint32", 253, -1, "", 1, 1, "", "", "", "", "", "", "", ""> @Timestamp;
	uint16<"Uint16", 0, -1, "", 1, 1, "ms", "", "", "", "", "Milliseconds past date_time", "", ""> @TimestampMs;
	uint16<"Uint16", 1, 0, "", 1, 1, "ms", "", "", "", "", "Array of millisecond times between beats", "", ""> @Time;
};
