#include "fitTypeDecls.idl"

enum<uint16,0xFFFF> CrunchExerciseName
{
	@BicycleCrunch = 0x0000, // Value: 0, Comment: 
	@CableCrunch = 0x0001, // Value: 1, Comment: 
	@CircularArmCrunch = 0x0002, // Value: 2, Comment: 
	@CrossedArmsCrunch = 0x0003, // Value: 3, Comment: 
	@WeightedCrossedArmsCrunch = 0x0004, // Value: 4, Comment: 
	@CrossLegReverseCrunch = 0x0005, // Value: 5, Comment: 
	@WeightedCrossLegReverseCrunch = 0x0006, // Value: 6, Comment: 
	@CrunchChop = 0x0007, // Value: 7, Comment: 
	@WeightedCrunchChop = 0x0008, // Value: 8, Comment: 
	@DoubleCrunch = 0x0009, // Value: 9, Comment: 
	@WeightedDoubleCrunch = 0x000A, // Value: 10, Comment: 
	@ElbowToKneeCrunch = 0x000B, // Value: 11, Comment: 
	@WeightedElbowToKneeCrunch = 0x000C, // Value: 12, Comment: 
	@FlutterKicks = 0x000D, // Value: 13, Comment: 
	@WeightedFlutterKicks = 0x000E, // Value: 14, Comment: 
	@FoamRollerReverseCrunchOnBench = 0x000F, // Value: 15, Comment: 
	@WeightedFoamRollerReverseCrunchOnBench = 0x0010, // Value: 16, Comment: 
	@FoamRollerReverseCrunchWithDumbbell = 0x0011, // Value: 17, Comment: 
	@FoamRollerReverseCrunchWithMedicineBall = 0x0012, // Value: 18, Comment: 
	@FrogPress = 0x0013, // Value: 19, Comment: 
	@HangingKneeRaiseObliqueCrunch = 0x0014, // Value: 20, Comment: 
	@WeightedHangingKneeRaiseObliqueCrunch = 0x0015, // Value: 21, Comment: 
	@HipCrossover = 0x0016, // Value: 22, Comment: 
	@WeightedHipCrossover = 0x0017, // Value: 23, Comment: 
	@HollowRock = 0x0018, // Value: 24, Comment: 
	@WeightedHollowRock = 0x0019, // Value: 25, Comment: 
	@InclineReverseCrunch = 0x001A, // Value: 26, Comment: 
	@WeightedInclineReverseCrunch = 0x001B, // Value: 27, Comment: 
	@KneelingCableCrunch = 0x001C, // Value: 28, Comment: 
	@KneelingCrossCrunch = 0x001D, // Value: 29, Comment: 
	@WeightedKneelingCrossCrunch = 0x001E, // Value: 30, Comment: 
	@KneelingObliqueCableCrunch = 0x001F, // Value: 31, Comment: 
	@KneesToElbow = 0x0020, // Value: 32, Comment: 
	@LegExtensions = 0x0021, // Value: 33, Comment: 
	@WeightedLegExtensions = 0x0022, // Value: 34, Comment: 
	@LegLevers = 0x0023, // Value: 35, Comment: 
	@McgillCurlUp = 0x0024, // Value: 36, Comment: 
	@WeightedMcgillCurlUp = 0x0025, // Value: 37, Comment: 
	@ModifiedPilatesRollUpWithBall = 0x0026, // Value: 38, Comment: 
	@WeightedModifiedPilatesRollUpWithBall = 0x0027, // Value: 39, Comment: 
	@PilatesCrunch = 0x0028, // Value: 40, Comment: 
	@WeightedPilatesCrunch = 0x0029, // Value: 41, Comment: 
	@PilatesRollUpWithBall = 0x002A, // Value: 42, Comment: 
	@WeightedPilatesRollUpWithBall = 0x002B, // Value: 43, Comment: 
	@RaisedLegsCrunch = 0x002C, // Value: 44, Comment: 
	@WeightedRaisedLegsCrunch = 0x002D, // Value: 45, Comment: 
	@ReverseCrunch = 0x002E, // Value: 46, Comment: 
	@WeightedReverseCrunch = 0x002F, // Value: 47, Comment: 
	@ReverseCrunchOnABench = 0x0030, // Value: 48, Comment: 
	@WeightedReverseCrunchOnABench = 0x0031, // Value: 49, Comment: 
	@ReverseCurlAndLift = 0x0032, // Value: 50, Comment: 
	@WeightedReverseCurlAndLift = 0x0033, // Value: 51, Comment: 
	@RotationalLift = 0x0034, // Value: 52, Comment: 
	@WeightedRotationalLift = 0x0035, // Value: 53, Comment: 
	@SeatedAlternatingReverseCrunch = 0x0036, // Value: 54, Comment: 
	@WeightedSeatedAlternatingReverseCrunch = 0x0037, // Value: 55, Comment: 
	@SeatedLegU = 0x0038, // Value: 56, Comment: 
	@WeightedSeatedLegU = 0x0039, // Value: 57, Comment: 
	@SideToSideCrunchAndWeave = 0x003A, // Value: 58, Comment: 
	@WeightedSideToSideCrunchAndWeave = 0x003B, // Value: 59, Comment: 
	@SingleLegReverseCrunch = 0x003C, // Value: 60, Comment: 
	@WeightedSingleLegReverseCrunch = 0x003D, // Value: 61, Comment: 
	@SkaterCrunchCross = 0x003E, // Value: 62, Comment: 
	@WeightedSkaterCrunchCross = 0x003F, // Value: 63, Comment: 
	@StandingCableCrunch = 0x0040, // Value: 64, Comment: 
	@StandingSideCrunch = 0x0041, // Value: 65, Comment: 
	@StepClimb = 0x0042, // Value: 66, Comment: 
	@WeightedStepClimb = 0x0043, // Value: 67, Comment: 
	@SwissBallCrunch = 0x0044, // Value: 68, Comment: 
	@SwissBallReverseCrunch = 0x0045, // Value: 69, Comment: 
	@WeightedSwissBallReverseCrunch = 0x0046, // Value: 70, Comment: 
	@SwissBallRussianTwist = 0x0047, // Value: 71, Comment: 
	@WeightedSwissBallRussianTwist = 0x0048, // Value: 72, Comment: 
	@SwissBallSideCrunch = 0x0049, // Value: 73, Comment: 
	@WeightedSwissBallSideCrunch = 0x004A, // Value: 74, Comment: 
	@ThoracicCrunchesOnFoamRoller = 0x004B, // Value: 75, Comment: 
	@WeightedThoracicCrunchesOnFoamRoller = 0x004C, // Value: 76, Comment: 
	@TricepsCrunch = 0x004D, // Value: 77, Comment: 
	@WeightedBicycleCrunch = 0x004E, // Value: 78, Comment: 
	@WeightedCrunch = 0x004F, // Value: 79, Comment: 
	@WeightedSwissBallCrunch = 0x0050, // Value: 80, Comment: 
	@ToesToBar = 0x0051, // Value: 81, Comment: 
	@WeightedToesToBar = 0x0052, // Value: 82, Comment: 
	@Crunch = 0x0053, // Value: 83, Comment: 
	@StraightLegCrunchWithBall = 0x0054 // Value: 84, Comment: 
};
