#include "fitTypeDecls.idl"

enum<uint16,0xFFFF> CommTimeoutType
{
	@WildcardPairingTimeout = 0x0000, // Value: 0, Comment: 
	@PairingTimeout = 0x0001, // Value: 1, Comment: 
	@ConnectionLost = 0x0002, // Value: 2, Comment: 
	@ConnectionTimeout = 0x0003 // Value: 3, Comment: 
};
