#include "fitTypeDecls.idl"

enum<uint16,0xFFFF> CoreExerciseName
{
	@AbsJabs = 0x0000, // Value: 0, Comment: 
	@WeightedAbsJabs = 0x0001, // Value: 1, Comment: 
	@AlternatingPlateReach = 0x0002, // Value: 2, Comment: 
	@BarbellRollout = 0x0003, // Value: 3, Comment: 
	@WeightedBarbellRollout = 0x0004, // Value: 4, Comment: 
	@BodyBarObliqueTwist = 0x0005, // Value: 5, Comment: 
	@CableCorePress = 0x0006, // Value: 6, Comment: 
	@CableSideBend = 0x0007, // Value: 7, Comment: 
	@SideBend = 0x0008, // Value: 8, Comment: 
	@WeightedSideBend = 0x0009, // Value: 9, Comment: 
	@CrescentCircle = 0x000A, // Value: 10, Comment: 
	@WeightedCrescentCircle = 0x000B, // Value: 11, Comment: 
	@CyclingRussianTwist = 0x000C, // Value: 12, Comment: 
	@WeightedCyclingRussianTwist = 0x000D, // Value: 13, Comment: 
	@ElevatedFeetRussianTwist = 0x000E, // Value: 14, Comment: 
	@WeightedElevatedFeetRussianTwist = 0x000F, // Value: 15, Comment: 
	@HalfTurkishGetUp = 0x0010, // Value: 16, Comment: 
	@KettlebellWindmill = 0x0011, // Value: 17, Comment: 
	@KneelingAbWheel = 0x0012, // Value: 18, Comment: 
	@WeightedKneelingAbWheel = 0x0013, // Value: 19, Comment: 
	@ModifiedFrontLever = 0x0014, // Value: 20, Comment: 
	@OpenKneeTucks = 0x0015, // Value: 21, Comment: 
	@WeightedOpenKneeTucks = 0x0016, // Value: 22, Comment: 
	@SideAbsLegLift = 0x0017, // Value: 23, Comment: 
	@WeightedSideAbsLegLift = 0x0018, // Value: 24, Comment: 
	@SwissBallJackknife = 0x0019, // Value: 25, Comment: 
	@WeightedSwissBallJackknife = 0x001A, // Value: 26, Comment: 
	@SwissBallPike = 0x001B, // Value: 27, Comment: 
	@WeightedSwissBallPike = 0x001C, // Value: 28, Comment: 
	@SwissBallRollout = 0x001D, // Value: 29, Comment: 
	@WeightedSwissBallRollout = 0x001E, // Value: 30, Comment: 
	@TriangleHipPress = 0x001F, // Value: 31, Comment: 
	@WeightedTriangleHipPress = 0x0020, // Value: 32, Comment: 
	@TrxSuspendedJackknife = 0x0021, // Value: 33, Comment: 
	@WeightedTrxSuspendedJackknife = 0x0022, // Value: 34, Comment: 
	@UBoat = 0x0023, // Value: 35, Comment: 
	@WeightedUBoat = 0x0024, // Value: 36, Comment: 
	@WindmillSwitches = 0x0025, // Value: 37, Comment: 
	@WeightedWindmillSwitches = 0x0026, // Value: 38, Comment: 
	@AlternatingSlideOut = 0x0027, // Value: 39, Comment: 
	@WeightedAlternatingSlideOut = 0x0028, // Value: 40, Comment: 
	@GhdBackExtensions = 0x0029, // Value: 41, Comment: 
	@WeightedGhdBackExtensions = 0x002A, // Value: 42, Comment: 
	@OverheadWalk = 0x002B, // Value: 43, Comment: 
	@Inchworm = 0x002C, // Value: 44, Comment: 
	@WeightedModifiedFrontLever = 0x002D, // Value: 45, Comment: 
	@RussianTwist = 0x002E, // Value: 46, Comment: 
	@ArmAndLegExtensionOnKnees = 0x0030, // Value: 48, Comment: 
	@Bicycle = 0x0031, // Value: 49, Comment: 
	@BicepCurlWithLegExtension = 0x0032, // Value: 50, Comment: 
	@CatCow = 0x0033, // Value: 51, Comment: 
	@Corkscrew = 0x0034, // Value: 52, Comment: 
	@CrissCross = 0x0035, // Value: 53, Comment: 
	@DoubleLegStretch = 0x0037, // Value: 55, Comment: 
	@KneeFolds = 0x0038, // Value: 56, Comment: 
	@LowerLift = 0x0039, // Value: 57, Comment: 
	@NeckPull = 0x003A, // Value: 58, Comment: 
	@PelvicClocks = 0x003B, // Value: 59, Comment: 
	@RollOver = 0x003C, // Value: 60, Comment: 
	@RollUp = 0x003D, // Value: 61, Comment: 
	@Rolling = 0x003E, // Value: 62, Comment: 
	@Rowing1 = 0x003F, // Value: 63, Comment: 
	@Rowing2 = 0x0040, // Value: 64, Comment: 
	@Scissors = 0x0041, // Value: 65, Comment: 
	@SingleLegCircles = 0x0042, // Value: 66, Comment: 
	@SingleLegStretch = 0x0043, // Value: 67, Comment: 
	@Swan = 0x0045, // Value: 69, Comment: 
	@Swimming = 0x0046, // Value: 70, Comment: 
	@Teaser = 0x0047, // Value: 71, Comment: 
	@TheHundred = 0x0048 // Value: 72, Comment: 
};
