#include "fitTypeDecls.idl"

enum<byte,0xFF> DayOfWeek
{
	@Sunday = 0x00, // Value: 0, Comment: 
	@Monday = 0x01, // Value: 1, Comment: 
	@Tuesday = 0x02, // Value: 2, Comment: 
	@Wednesday = 0x03, // Value: 3, Comment: 
	@Thursday = 0x04, // Value: 4, Comment: 
	@Friday = 0x05, // Value: 5, Comment: 
	@Saturday = 0x06 // Value: 6, Comment: 
};
