#include "fitTypeDecls.idl"
#include "fitAllTypes.idl"

struct<"DeviceInfo", ""> DeviceInfo {
	uint32<"Uint32", 253, -1, "", 1, 1, "s", "", "", "", "", "", "", "1"> @Timestamp;
	DeviceIndex<"Enum", 0, -1, "", 1, 1, "", "", "", "", "", "", "", "1"> @DeviceIndex;
	uint8<"Uint8", 1, -1, "", 1, 1, "", "", "", "", "", "", "", "1"> @DeviceType
	{
		uint8<"Uint8", "", 1, 1, "", "", "", "source_type", "bluetooth_low_energy", "", "", ""> @BleDeviceType;
		uint8<"Uint8", "", 1, 1, "", "", "", "source_type", "antplus", "", "", "1"> @AntplusDeviceType;
		uint8<"Uint8", "", 1, 1, "", "", "", "source_type", "ant", "", "", "1"> @AntDeviceType;
		uint8<"Uint8", "", 1, 1, "", "", "", "source_type", "local", "", "", "1"> @LocalDeviceType;
	};
	Manufacturer<"Enum", 2, -1, "", 1, 1, "", "", "", "", "", "", "", "1"> @Manufacturer;
	uint32<"Uint32z", 3, -1, "", 1, 1, "", "", "", "", "", "", "", "1"> @SerialNumber;
	uint16<"Uint16", 4, -1, "", 1, 1, "", "", "", "", "", "", "", "1"> @Product
	{
		uint16<"Uint16", "", 1, 1, "", "", "", "manufacturer", "favero_electronics", "", "", ""> @FaveroProduct;
		uint16<"Uint16", "", 1, 1, "", "", "", "manufacturer,manufacturer,manufacturer,manufacturer", "garmin,dynastream,dynastream_oem,tacx", "", "", "1"> @GarminProduct;
	};
	uint16<"Uint16", 5, -1, "", 100, 1, "", "", "", "", "", "", "", "1"> @SoftwareVersion;
	uint8<"Uint8", 6, -1, "", 1, 1, "", "", "", "", "", "", "", "1"> @HardwareVersion;
	uint32<"Uint32", 7, -1, "", 1, 1, "s", "", "", "", "", "Reset by new battery or charge.", "", "1"> @CumOperatingTime;
	uint16<"Uint16", 10, -1, "", 256, 1, "V", "", "", "", "", "", "", "1"> @BatteryVoltage;
	BatteryStatus<"Enum", 11, -1, "", 1, 1, "", "", "", "", "", "", "", "1"> @BatteryStatus;
	BodyLocation<"Enum", 18, -1, "", 1, 1, "", "", "", "", "", "Indicates the location of the sensor", "", "1"> @SensorPosition;
	string<"String", 19, -1, "", 1, 1, "", "", "", "", "", "Used to describe the sensor or location", "", "1"> @Descriptor;
	uint8<"Uint8z", 20, -1, "", 1, 1, "", "", "", "", "", "", "", "1"> @AntTransmissionType;
	uint16<"Uint16z", 21, -1, "", 1, 1, "", "", "", "", "", "", "", "1"> @AntDeviceNumber;
	AntNetwork<"Enum", 22, -1, "", 1, 1, "", "", "", "", "", "", "", "1"> @AntNetwork;
	SourceType<"Enum", 25, -1, "", 1, 1, "", "", "", "", "", "", "", "1"> @SourceType;
	string<"String", 27, -1, "", 1, 1, "", "", "", "", "", "Optional free form string to indicate the devices name or model", "", "20"> @ProductName;
	uint8<"Uint8", 32, -1, "", 1, 1, "%", "", "", "", "", "", "", ""> @BatteryLevel;
};
