#include "fitTypeDecls.idl"

enum<uint16,0xFFFF> DeadliftExerciseName
{
	@BarbellDeadlift = 0x0000, // Value: 0, Comment: 
	@BarbellStraightLegDeadlift = 0x0001, // Value: 1, Comment: 
	@DumbbellDeadlift = 0x0002, // Value: 2, Comment: 
	@DumbbellSingleLegDeadliftToRow = 0x0003, // Value: 3, Comment: 
	@DumbbellStraightLegDeadlift = 0x0004, // Value: 4, Comment: 
	@KettlebellFloorToShelf = 0x0005, // Value: 5, Comment: 
	@OneArmOneLegDeadlift = 0x0006, // Value: 6, Comment: 
	@RackPull = 0x0007, // Value: 7, Comment: 
	@RotationalDumbbellStraightLegDeadlift = 0x0008, // Value: 8, Comment: 
	@SingleArmDeadlift = 0x0009, // Value: 9, Comment: 
	@SingleLegBarbellDeadlift = 0x000A, // Value: 10, Comment: 
	@SingleLegBarbellStraightLegDeadlift = 0x000B, // Value: 11, Comment: 
	@SingleLegDeadliftWithBarbell = 0x000C, // Value: 12, Comment: 
	@SingleLegRdlCircuit = 0x000D, // Value: 13, Comment: 
	@SingleLegRomanianDeadliftWithDumbbell = 0x000E, // Value: 14, Comment: 
	@SumoDeadlift = 0x000F, // Value: 15, Comment: 
	@SumoDeadliftHighPull = 0x0010, // Value: 16, Comment: 
	@TrapBarDeadlift = 0x0011, // Value: 17, Comment: 
	@WideGripBarbellDeadlift = 0x0012 // Value: 18, Comment: 
};
