#include "fitTypeDecls.idl"

enum<byte,0xFF> DisplayOrientation
{
	@Auto = 0x00, // Value: 0, Comment: 
	@Portrait = 0x01, // Value: 1, Comment: 
	@Landscape = 0x02, // Value: 2, Comment: 
	@PortraitFlipped = 0x03, // Value: 3, Comment: 
	@LandscapeFlipped = 0x04 // Value: 4, Comment: 
};
