#include "fitTypeDecls.idl"

enum<byte,0xFF> ExdDescriptors
{
	@BikeLightBatteryStatus = 0x00, // Value: 0, Comment: 
	@BeamAngleStatus = 0x01, // Value: 1, Comment: 
	@BateryLevel = 0x02, // Value: 2, Comment: 
	@LightNetworkMode = 0x03, // Value: 3, Comment: 
	@NumberLightsConnected = 0x04, // Value: 4, Comment: 
	@Cadence = 0x05, // Value: 5, Comment: 
	@Distance = 0x06, // Value: 6, Comment: 
	@EstimatedTimeOfArrival = 0x07, // Value: 7, Comment: 
	@Heading = 0x08, // Value: 8, Comment: 
	@Time = 0x09, // Value: 9, Comment: 
	@BatteryLevel = 0x0A, // Value: 10, Comment: 
	@TrainerResistance = 0x0B, // Value: 11, Comment: 
	@TrainerTargetPower = 0x0C, // Value: 12, Comment: 
	@TimeSeated = 0x0D, // Value: 13, Comment: 
	@TimeStanding = 0x0E, // Value: 14, Comment: 
	@Elevation = 0x0F, // Value: 15, Comment: 
	@Grade = 0x10, // Value: 16, Comment: 
	@Ascent = 0x11, // Value: 17, Comment: 
	@Descent = 0x12, // Value: 18, Comment: 
	@VerticalSpeed = 0x13, // Value: 19, Comment: 
	@Di2BatteryLevel = 0x14, // Value: 20, Comment: 
	@FrontGear = 0x15, // Value: 21, Comment: 
	@RearGear = 0x16, // Value: 22, Comment: 
	@GearRatio = 0x17, // Value: 23, Comment: 
	@HeartRate = 0x18, // Value: 24, Comment: 
	@HeartRateZone = 0x19, // Value: 25, Comment: 
	@TimeInHeartRateZone = 0x1A, // Value: 26, Comment: 
	@HeartRateReserve = 0x1B, // Value: 27, Comment: 
	@Calories = 0x1C, // Value: 28, Comment: 
	@GpsAccuracy = 0x1D, // Value: 29, Comment: 
	@GpsSignalStrength = 0x1E, // Value: 30, Comment: 
	@Temperature = 0x1F, // Value: 31, Comment: 
	@TimeOfDay = 0x20, // Value: 32, Comment: 
	@Balance = 0x21, // Value: 33, Comment: 
	@PedalSmoothness = 0x22, // Value: 34, Comment: 
	@Power = 0x23, // Value: 35, Comment: 
	@FunctionalThresholdPower = 0x24, // Value: 36, Comment: 
	@IntensityFactor = 0x25, // Value: 37, Comment: 
	@Work = 0x26, // Value: 38, Comment: 
	@PowerRatio = 0x27, // Value: 39, Comment: 
	@NormalizedPower = 0x28, // Value: 40, Comment: 
	@TrainingStressScore = 0x29, // Value: 41, Comment: 
	@TimeOnZone = 0x2A, // Value: 42, Comment: 
	@Speed = 0x2B, // Value: 43, Comment: 
	@Laps = 0x2C, // Value: 44, Comment: 
	@Reps = 0x2D, // Value: 45, Comment: 
	@WorkoutStep = 0x2E, // Value: 46, Comment: 
	@CourseDistance = 0x2F, // Value: 47, Comment: 
	@NavigationDistance = 0x30, // Value: 48, Comment: 
	@CourseEstimatedTimeOfArrival = 0x31, // Value: 49, Comment: 
	@NavigationEstimatedTimeOfArrival = 0x32, // Value: 50, Comment: 
	@CourseTime = 0x33, // Value: 51, Comment: 
	@NavigationTime = 0x34, // Value: 52, Comment: 
	@CourseHeading = 0x35, // Value: 53, Comment: 
	@NavigationHeading = 0x36, // Value: 54, Comment: 
	@PowerZone = 0x37, // Value: 55, Comment: 
	@TorqueEffectiveness = 0x38, // Value: 56, Comment: 
	@TimerTime = 0x39, // Value: 57, Comment: 
	@PowerWeightRatio = 0x3A, // Value: 58, Comment: 
	@LeftPlatformCenterOffset = 0x3B, // Value: 59, Comment: 
	@RightPlatformCenterOffset = 0x3C, // Value: 60, Comment: 
	@LeftPowerPhaseStartAngle = 0x3D, // Value: 61, Comment: 
	@RightPowerPhaseStartAngle = 0x3E, // Value: 62, Comment: 
	@LeftPowerPhaseFinishAngle = 0x3F, // Value: 63, Comment: 
	@RightPowerPhaseFinishAngle = 0x40, // Value: 64, Comment: 
	@Gears = 0x41, // Value: 65, Comment: 
	@Pace = 0x42, // Value: 66, Comment: 
	@TrainingEffect = 0x43, // Value: 67, Comment: 
	@VerticalOscillation = 0x44, // Value: 68, Comment: 
	@VerticalRatio = 0x45, // Value: 69, Comment: 
	@GroundContactTime = 0x46, // Value: 70, Comment: 
	@LeftGroundContactTimeBalance = 0x47, // Value: 71, Comment: 
	@RightGroundContactTimeBalance = 0x48, // Value: 72, Comment: 
	@StrideLength = 0x49, // Value: 73, Comment: 
	@RunningCadence = 0x4A, // Value: 74, Comment: 
	@PerformanceCondition = 0x4B, // Value: 75, Comment: 
	@CourseType = 0x4C, // Value: 76, Comment: 
	@TimeInPowerZone = 0x4D, // Value: 77, Comment: 
	@NavigationTurn = 0x4E, // Value: 78, Comment: 
	@CourseLocation = 0x4F, // Value: 79, Comment: 
	@NavigationLocation = 0x50, // Value: 80, Comment: 
	@Compass = 0x51, // Value: 81, Comment: 
	@GearCombo = 0x52, // Value: 82, Comment: 
	@MuscleOxygen = 0x53, // Value: 83, Comment: 
	@Icon = 0x54, // Value: 84, Comment: 
	@CompassHeading = 0x55, // Value: 85, Comment: 
	@GpsHeading = 0x56, // Value: 86, Comment: 
	@GpsElevation = 0x57, // Value: 87, Comment: 
	@AnaerobicTrainingEffect = 0x58, // Value: 88, Comment: 
	@Course = 0x59, // Value: 89, Comment: 
	@OffCourse = 0x5A, // Value: 90, Comment: 
	@GlideRatio = 0x5B, // Value: 91, Comment: 
	@VerticalDistance = 0x5C, // Value: 92, Comment: 
	@Vmg = 0x5D, // Value: 93, Comment: 
	@AmbientPressure = 0x5E, // Value: 94, Comment: 
	@Pressure = 0x5F, // Value: 95, Comment: 
	@Vam = 0x60 // Value: 96, Comment: 
};
