#include "fitTypeDecls.idl"

enum<uint16,0xFFFF> GarminProduct
{
	@Hrm1 = 0x0001, // Value: 1, Comment: 
	@Axh01 = 0x0002, // Value: 2, Comment: 
	@Axb01 = 0x0003, // Value: 3, Comment: 
	@Axb02 = 0x0004, // Value: 4, Comment: 
	@Hrm2ss = 0x0005, // Value: 5, Comment: 
	@DsiAlf02 = 0x0006, // Value: 6, Comment: 
	@Hrm3ss = 0x0007, // Value: 7, Comment: 
	@HrmRunSingleByteProductId = 0x0008, // Value: 8, Comment: 
	@Bsm = 0x0009, // Value: 9, Comment: 
	@Bcm = 0x000A, // Value: 10, Comment: 
	@Axs01 = 0x000B, // Value: 11, Comment: 
	@HrmTriSingleByteProductId = 0x000C, // Value: 12, Comment: 
	@Hrm4RunSingleByteProductId = 0x000D, // Value: 13, Comment: 
	@Fr225SingleByteProductId = 0x000E, // Value: 14, Comment: 
	@Gen3BsmSingleByteProductId = 0x000F, // Value: 15, Comment: 
	@Gen3BcmSingleByteProductId = 0x0010, // Value: 16, Comment: 
	@HrmFitSingleByteProductId = 0x0016, // Value: 22, Comment: 
	@OHR = 0x00FF, // Value: 255, Comment: 
	@Fr301China = 0x01D9, // Value: 473, Comment: 
	@Fr301Japan = 0x01DA, // Value: 474, Comment: 
	@Fr301Korea = 0x01DB, // Value: 475, Comment: 
	@Fr301Taiwan = 0x01EE, // Value: 494, Comment: 
	@Fr405 = 0x02CD, // Value: 717, Comment: 
	@Fr50 = 0x030E, // Value: 782, Comment: 
	@Fr405Japan = 0x03DB, // Value: 987, Comment: 
	@Fr60 = 0x03DC, // Value: 988, Comment: 
	@DsiAlf01 = 0x03F3, // Value: 1011, Comment: 
	@Fr310xt = 0x03FA, // Value: 1018, Comment: 
	@Edge500 = 0x040C, // Value: 1036, Comment: 
	@Fr110 = 0x0464, // Value: 1124, Comment: 
	@Edge800 = 0x0491, // Value: 1169, Comment: 
	@Edge500Taiwan = 0x04AF, // Value: 1199, Comment: 
	@Edge500Japan = 0x04BD, // Value: 1213, Comment: 
	@Chirp = 0x04E5, // Value: 1253, Comment: 
	@Fr110Japan = 0x04FA, // Value: 1274, Comment: 
	@Edge200 = 0x052D, // Value: 1325, Comment: 
	@Fr910xt = 0x0530, // Value: 1328, Comment: 
	@Edge800Taiwan = 0x0535, // Value: 1333, Comment: 
	@Edge800Japan = 0x0536, // Value: 1334, Comment: 
	@Alf04 = 0x053D, // Value: 1341, Comment: 
	@Fr610 = 0x0541, // Value: 1345, Comment: 
	@Fr210Japan = 0x0550, // Value: 1360, Comment: 
	@VectorSs = 0x0564, // Value: 1380, Comment: 
	@VectorCp = 0x0565, // Value: 1381, Comment: 
	@Edge800China = 0x056A, // Value: 1386, Comment: 
	@Edge500China = 0x056B, // Value: 1387, Comment: 
	@ApproachG10 = 0x057D, // Value: 1405, Comment: 
	@Fr610Japan = 0x0582, // Value: 1410, Comment: 
	@Edge500Korea = 0x058E, // Value: 1422, Comment: 
	@Fr70 = 0x059C, // Value: 1436, Comment: 
	@Fr310xt4t = 0x05A6, // Value: 1446, Comment: 
	@Amx = 0x05B5, // Value: 1461, Comment: 
	@Fr10 = 0x05CA, // Value: 1482, Comment: 
	@Edge800Korea = 0x05D9, // Value: 1497, Comment: 
	@Swim = 0x05DB, // Value: 1499, Comment: 
	@Fr910xtChina = 0x0601, // Value: 1537, Comment: 
	@Fenix = 0x060F, // Value: 1551, Comment: 
	@Edge200Taiwan = 0x0613, // Value: 1555, Comment: 
	@Edge510 = 0x0619, // Value: 1561, Comment: 
	@Edge810 = 0x061F, // Value: 1567, Comment: 
	@Tempe = 0x0622, // Value: 1570, Comment: 
	@Fr910xtJapan = 0x0640, // Value: 1600, Comment: 
	@Fr620 = 0x0657, // Value: 1623, Comment: 
	@Fr220 = 0x0660, // Value: 1632, Comment: 
	@Fr910xtKorea = 0x0680, // Value: 1664, Comment: 
	@Fr10Japan = 0x0698, // Value: 1688, Comment: 
	@Edge810Japan = 0x06B9, // Value: 1721, Comment: 
	@VirbElite = 0x06C7, // Value: 1735, Comment: 
	@EdgeTouring = 0x06C8, // Value: 1736, Comment: 
	@Edge510Japan = 0x06CE, // Value: 1742, Comment: 
	@HrmTri = 0x06CF, // Value: 1743, Comment: 
	@HrmRun = 0x06D8, // Value: 1752, Comment: 
	@Fr920xt = 0x06E5, // Value: 1765, Comment: 
	@Edge510Asia = 0x071D, // Value: 1821, Comment: 
	@Edge810China = 0x071E, // Value: 1822, Comment: 
	@Edge810Taiwan = 0x071F, // Value: 1823, Comment: 
	@Edge1000 = 0x072C, // Value: 1836, Comment: 
	@VivoFit = 0x072D, // Value: 1837, Comment: 
	@VirbRemote = 0x073D, // Value: 1853, Comment: 
	@VivoKi = 0x075D, // Value: 1885, Comment: 
	@Fr15 = 0x076F, // Value: 1903, Comment: 
	@VivoActive = 0x0773, // Value: 1907, Comment: 
	@Edge510Korea = 0x077E, // Value: 1918, Comment: 
	@Fr620Japan = 0x0788, // Value: 1928, Comment: 
	@Fr620China = 0x0789, // Value: 1929, Comment: 
	@Fr220Japan = 0x078A, // Value: 1930, Comment: 
	@Fr220China = 0x078B, // Value: 1931, Comment: 
	@ApproachS6 = 0x0790, // Value: 1936, Comment: 
	@VivoSmart = 0x07A4, // Value: 1956, Comment: 
	@Fenix2 = 0x07AF, // Value: 1967, Comment: 
	@Epix = 0x07C4, // Value: 1988, Comment: 
	@Fenix3 = 0x0802, // Value: 2050, Comment: 
	@Edge1000Taiwan = 0x0804, // Value: 2052, Comment: 
	@Edge1000Japan = 0x0805, // Value: 2053, Comment: 
	@Fr15Japan = 0x080D, // Value: 2061, Comment: 
	@Edge520 = 0x0813, // Value: 2067, Comment: 
	@Edge1000China = 0x0816, // Value: 2070, Comment: 
	@Fr620Russia = 0x0818, // Value: 2072, Comment: 
	@Fr220Russia = 0x0819, // Value: 2073, Comment: 
	@VectorS = 0x081F, // Value: 2079, Comment: 
	@Edge1000Korea = 0x0834, // Value: 2100, Comment: 
	@Fr920xtTaiwan = 0x0852, // Value: 2130, Comment: 
	@Fr920xtChina = 0x0853, // Value: 2131, Comment: 
	@Fr920xtJapan = 0x0854, // Value: 2132, Comment: 
	@Virbx = 0x0856, // Value: 2134, Comment: 
	@VivoSmartApac = 0x0857, // Value: 2135, Comment: 
	@EtrexTouch = 0x085C, // Value: 2140, Comment: 
	@Edge25 = 0x0863, // Value: 2147, Comment: 
	@Fr25 = 0x0864, // Value: 2148, Comment: 
	@VivoFit2 = 0x0866, // Value: 2150, Comment: 
	@Fr225 = 0x0869, // Value: 2153, Comment: 
	@Fr630 = 0x086C, // Value: 2156, Comment: 
	@Fr230 = 0x086D, // Value: 2157, Comment: 
	@Fr735xt = 0x086E, // Value: 2158, Comment: 
	@VivoActiveApac = 0x0870, // Value: 2160, Comment: 
	@Vector2 = 0x0871, // Value: 2161, Comment: 
	@Vector2s = 0x0872, // Value: 2162, Comment: 
	@Virbxe = 0x087C, // Value: 2172, Comment: 
	@Fr620Taiwan = 0x087D, // Value: 2173, Comment: 
	@Fr220Taiwan = 0x087E, // Value: 2174, Comment: 
	@Truswing = 0x087F, // Value: 2175, Comment: 
	@D2airvenu = 0x088B, // Value: 2187, Comment: 
	@Fenix3China = 0x088C, // Value: 2188, Comment: 
	@Fenix3Twn = 0x088D, // Value: 2189, Comment: 
	@VariaHeadlight = 0x0890, // Value: 2192, Comment: 
	@VariaTaillightOld = 0x0891, // Value: 2193, Comment: 
	@EdgeExplore1000 = 0x089C, // Value: 2204, Comment: 
	@Fr225Asia = 0x08AB, // Value: 2219, Comment: 
	@VariaRadarTaillight = 0x08B1, // Value: 2225, Comment: 
	@VariaRadarDisplay = 0x08B2, // Value: 2226, Comment: 
	@Edge20 = 0x08BE, // Value: 2238, Comment: 
	@Edge520Asia = 0x08D4, // Value: 2260, Comment: 
	@Edge520Japan = 0x08D5, // Value: 2261, Comment: 
	@D2Bravo = 0x08D6, // Value: 2262, Comment: 
	@ApproachS20 = 0x08DA, // Value: 2266, Comment: 
	@VivoSmart2 = 0x08DF, // Value: 2271, Comment: 
	@Edge1000Thai = 0x08E2, // Value: 2274, Comment: 
	@VariaRemote = 0x08E4, // Value: 2276, Comment: 
	@Edge25Asia = 0x08F0, // Value: 2288, Comment: 
	@Edge25Jpn = 0x08F1, // Value: 2289, Comment: 
	@Edge20Asia = 0x08F2, // Value: 2290, Comment: 
	@ApproachX40 = 0x08F4, // Value: 2292, Comment: 
	@Fenix3Japan = 0x08F5, // Value: 2293, Comment: 
	@VivoSmartEmea = 0x08F6, // Value: 2294, Comment: 
	@Fr630Asia = 0x0906, // Value: 2310, Comment: 
	@Fr630Jpn = 0x0907, // Value: 2311, Comment: 
	@Fr230Jpn = 0x0909, // Value: 2313, Comment: 
	@Hrm4Run = 0x0917, // Value: 2327, Comment: 
	@EpixJapan = 0x091C, // Value: 2332, Comment: 
	@VivoActiveHr = 0x0921, // Value: 2337, Comment: 
	@VivoSmartGpsHr = 0x092B, // Value: 2347, Comment: 
	@VivoSmartHr = 0x092C, // Value: 2348, Comment: 
	@VivoSmartHrAsia = 0x0939, // Value: 2361, Comment: 
	@VivoSmartGpsHrAsia = 0x093A, // Value: 2362, Comment: 
	@VivoMove = 0x0940, // Value: 2368, Comment: 
	@VariaTaillight = 0x094B, // Value: 2379, Comment: 
	@Fr235Asia = 0x095C, // Value: 2396, Comment: 
	@Fr235Japan = 0x095D, // Value: 2397, Comment: 
	@VariaVision = 0x095E, // Value: 2398, Comment: 
	@VivoFit3 = 0x0966, // Value: 2406, Comment: 
	@Fenix3Korea = 0x0967, // Value: 2407, Comment: 
	@Fenix3Sea = 0x0968, // Value: 2408, Comment: 
	@Fenix3Hr = 0x096D, // Value: 2413, Comment: 
	@VirbUltra30 = 0x0971, // Value: 2417, Comment: 
	@IndexSmartScale = 0x097D, // Value: 2429, Comment: 
	@Fr235 = 0x097F, // Value: 2431, Comment: 
	@Fenix3Chronos = 0x0980, // Value: 2432, Comment: 
	@Oregon7xx = 0x0989, // Value: 2441, Comment: 
	@Rino7xx = 0x098C, // Value: 2444, Comment: 
	@EpixKorea = 0x0999, // Value: 2457, Comment: 
	@Fenix3HrChn = 0x09A9, // Value: 2473, Comment: 
	@Fenix3HrTwn = 0x09AA, // Value: 2474, Comment: 
	@Fenix3HrJpn = 0x09AB, // Value: 2475, Comment: 
	@Fenix3HrSea = 0x09AC, // Value: 2476, Comment: 
	@Fenix3HrKor = 0x09AD, // Value: 2477, Comment: 
	@Nautix = 0x09C0, // Value: 2496, Comment: 
	@VivoActiveHrApac = 0x09C1, // Value: 2497, Comment: 
	@Fr35 = 0x09C7, // Value: 2503, Comment: 
	@Oregon7xxWw = 0x09D0, // Value: 2512, Comment: 
	@Edge820 = 0x09E2, // Value: 2530, Comment: 
	@EdgeExplore820 = 0x09E3, // Value: 2531, Comment: 
	@Fr735xtApac = 0x09E5, // Value: 2533, Comment: 
	@Fr735xtJapan = 0x09E6, // Value: 2534, Comment: 
	@Fenix5s = 0x09F0, // Value: 2544, Comment: 
	@D2BravoTitanium = 0x09F3, // Value: 2547, Comment: 
	@VariaUt800 = 0x0A07, // Value: 2567, Comment: 
	@RunningDynamicsPod = 0x0A21, // Value: 2593, Comment: 
	@Edge820China = 0x0A27, // Value: 2599, Comment: 
	@Edge820Japan = 0x0A28, // Value: 2600, Comment: 
	@Fenix5x = 0x0A2C, // Value: 2604, Comment: 
	@VivoFitJr = 0x0A2E, // Value: 2606, Comment: 
	@VivoSmart3 = 0x0A3E, // Value: 2622, Comment: 
	@VivoSport = 0x0A3F, // Value: 2623, Comment: 
	@Edge820Taiwan = 0x0A44, // Value: 2628, Comment: 
	@Edge820Korea = 0x0A45, // Value: 2629, Comment: 
	@Edge820Sea = 0x0A46, // Value: 2630, Comment: 
	@Fr35Hebrew = 0x0A5A, // Value: 2650, Comment: 
	@ApproachS60 = 0x0A60, // Value: 2656, Comment: 
	@Fr35Apac = 0x0A6B, // Value: 2667, Comment: 
	@Fr35Japan = 0x0A6C, // Value: 2668, Comment: 
	@Fenix3ChronosAsia = 0x0A73, // Value: 2675, Comment: 
	@Virb360 = 0x0A7F, // Value: 2687, Comment: 
	@Fr935 = 0x0A83, // Value: 2691, Comment: 
	@Fenix5 = 0x0A89, // Value: 2697, Comment: 
	@Vivoactive3 = 0x0A8C, // Value: 2700, Comment: 
	@Fr235ChinaNfc = 0x0AAD, // Value: 2733, Comment: 
	@Foretrex601701 = 0x0AD1, // Value: 2769, Comment: 
	@VivoMoveHr = 0x0AD4, // Value: 2772, Comment: 
	@Edge1030 = 0x0A99, // Value: 2713, Comment: 
	@Fr35Sea = 0x0AA7, // Value: 2727, Comment: 
	@Vector3 = 0x0AE3, // Value: 2787, Comment: 
	@Fenix5Asia = 0x0AEC, // Value: 2796, Comment: 
	@Fenix5sAsia = 0x0AED, // Value: 2797, Comment: 
	@Fenix5xAsia = 0x0AEE, // Value: 2798, Comment: 
	@ApproachZ80 = 0x0AF6, // Value: 2806, Comment: 
	@Fr35Korea = 0x0AFE, // Value: 2814, Comment: 
	@D2charlie = 0x0B03, // Value: 2819, Comment: 
	@VivoSmart3Apac = 0x0B0F, // Value: 2831, Comment: 
	@VivoSportApac = 0x0B10, // Value: 2832, Comment: 
	@Fr935Asia = 0x0B11, // Value: 2833, Comment: 
	@Descent = 0x0B2B, // Value: 2859, Comment: 
	@VivoFit4 = 0x0B3E, // Value: 2878, Comment: 
	@Fr645 = 0x0B46, // Value: 2886, Comment: 
	@Fr645m = 0x0B48, // Value: 2888, Comment: 
	@Fr30 = 0x0B4B, // Value: 2891, Comment: 
	@Fenix5sPlus = 0x0B54, // Value: 2900, Comment: 
	@Edge130 = 0x0B5D, // Value: 2909, Comment: 
	@Edge1030Asia = 0x0B6C, // Value: 2924, Comment: 
	@Vivosmart4 = 0x0B6F, // Value: 2927, Comment: 
	@VivoMoveHrAsia = 0x0B81, // Value: 2945, Comment: 
	@ApproachX10 = 0x0B92, // Value: 2962, Comment: 
	@Fr30Asia = 0x0BA1, // Value: 2977, Comment: 
	@Vivoactive3mW = 0x0BAC, // Value: 2988, Comment: 
	@Fr645Asia = 0x0BBB, // Value: 3003, Comment: 
	@Fr645mAsia = 0x0BBC, // Value: 3004, Comment: 
	@EdgeExplore = 0x0BC3, // Value: 3011, Comment: 
	@Gpsmap66 = 0x0BD4, // Value: 3028, Comment: 
	@ApproachS10 = 0x0BE9, // Value: 3049, Comment: 
	@Vivoactive3mL = 0x0BFA, // Value: 3066, Comment: 
	@ApproachG80 = 0x0C0D, // Value: 3085, Comment: 
	@Edge130Asia = 0x0C14, // Value: 3092, Comment: 
	@Edge1030Bontrager = 0x0C17, // Value: 3095, Comment: 
	@Fenix5Plus = 0x0C26, // Value: 3110, Comment: 
	@Fenix5xPlus = 0x0C27, // Value: 3111, Comment: 
	@Edge520Plus = 0x0C28, // Value: 3112, Comment: 
	@Fr945 = 0x0C29, // Value: 3113, Comment: 
	@Edge530 = 0x0C31, // Value: 3121, Comment: 
	@Edge830 = 0x0C32, // Value: 3122, Comment: 
	@InstinctEsports = 0x0C36, // Value: 3126, Comment: 
	@Fenix5sPlusApac = 0x0C3E, // Value: 3134, Comment: 
	@Fenix5xPlusApac = 0x0C3F, // Value: 3135, Comment: 
	@Edge520PlusApac = 0x0C46, // Value: 3142, Comment: 
	@DescentT1 = 0x0C47, // Value: 3143, Comment: 
	@Fr235lAsia = 0x0C48, // Value: 3144, Comment: 
	@Fr245Asia = 0x0C49, // Value: 3145, Comment: 
	@VivoActive3mApac = 0x0C5B, // Value: 3163, Comment: 
	@Gen3Bsm = 0x0C78, // Value: 3192, Comment: 
	@Gen3Bcm = 0x0C79, // Value: 3193, Comment: 
	@VivoSmart4Asia = 0x0C92, // Value: 3218, Comment: 
	@Vivoactive4Small = 0x0C98, // Value: 3224, Comment: 
	@Vivoactive4Large = 0x0C99, // Value: 3225, Comment: 
	@Venu = 0x0C9A, // Value: 3226, Comment: 
	@MarqDriver = 0x0CAE, // Value: 3246, Comment: 
	@MarqAviator = 0x0CAF, // Value: 3247, Comment: 
	@MarqCaptain = 0x0CB0, // Value: 3248, Comment: 
	@MarqCommander = 0x0CB1, // Value: 3249, Comment: 
	@MarqExpedition = 0x0CB2, // Value: 3250, Comment: 
	@MarqAthlete = 0x0CB3, // Value: 3251, Comment: 
	@DescentMk2 = 0x0CBA, // Value: 3258, Comment: 
	@Gpsmap66i = 0x0CD4, // Value: 3284, Comment: 
	@Fenix6SSport = 0x0CD7, // Value: 3287, Comment: 
	@Fenix6S = 0x0CD8, // Value: 3288, Comment: 
	@Fenix6Sport = 0x0CD9, // Value: 3289, Comment: 
	@Fenix6 = 0x0CDA, // Value: 3290, Comment: 
	@Fenix6x = 0x0CDB, // Value: 3291, Comment: 
	@HrmDual = 0x0CE3, // Value: 3299, Comment: 
	@HrmPro = 0x0CE4, // Value: 3300, Comment: 
	@VivoMove3Premium = 0x0CEC, // Value: 3308, Comment: 
	@ApproachS40 = 0x0CF2, // Value: 3314, Comment: 
	@Fr245mAsia = 0x0CF9, // Value: 3321, Comment: 
	@Edge530Apac = 0x0D15, // Value: 3349, Comment: 
	@Edge830Apac = 0x0D16, // Value: 3350, Comment: 
	@VivoMove3 = 0x0D32, // Value: 3378, Comment: 
	@VivoActive4SmallAsia = 0x0D3B, // Value: 3387, Comment: 
	@VivoActive4LargeAsia = 0x0D3C, // Value: 3388, Comment: 
	@VivoActive4OledAsia = 0x0D3D, // Value: 3389, Comment: 
	@Swim2 = 0x0D4D, // Value: 3405, Comment: 
	@MarqDriverAsia = 0x0D5C, // Value: 3420, Comment: 
	@MarqAviatorAsia = 0x0D5D, // Value: 3421, Comment: 
	@VivoMove3Asia = 0x0D5E, // Value: 3422, Comment: 
	@Fr945Asia = 0x0D71, // Value: 3441, Comment: 
	@VivoActive3tChn = 0x0D76, // Value: 3446, Comment: 
	@MarqCaptainAsia = 0x0D78, // Value: 3448, Comment: 
	@MarqCommanderAsia = 0x0D79, // Value: 3449, Comment: 
	@MarqExpeditionAsia = 0x0D7A, // Value: 3450, Comment: 
	@MarqAthleteAsia = 0x0D7B, // Value: 3451, Comment: 
	@IndexSmartScale2 = 0x0D85, // Value: 3461, Comment: 
	@InstinctSolar = 0x0D8A, // Value: 3466, Comment: 
	@Fr45Asia = 0x0D8D, // Value: 3469, Comment: 
	@Vivoactive3Daimler = 0x0D91, // Value: 3473, Comment: 
	@LegacyRey = 0x0DAA, // Value: 3498, Comment: 
	@LegacyDarthVader = 0x0DAB, // Value: 3499, Comment: 
	@LegacyCaptainMarvel = 0x0DAC, // Value: 3500, Comment: 
	@LegacyFirstAvenger = 0x0DAD, // Value: 3501, Comment: 
	@Fenix6sSportAsia = 0x0DB8, // Value: 3512, Comment: 
	@Fenix6sAsia = 0x0DB9, // Value: 3513, Comment: 
	@Fenix6SportAsia = 0x0DBA, // Value: 3514, Comment: 
	@Fenix6Asia = 0x0DBB, // Value: 3515, Comment: 
	@Fenix6xAsia = 0x0DBC, // Value: 3516, Comment: 
	@LegacyCaptainMarvelAsia = 0x0DCF, // Value: 3535, Comment: 
	@LegacyFirstAvengerAsia = 0x0DD0, // Value: 3536, Comment: 
	@LegacyReyAsia = 0x0DD1, // Value: 3537, Comment: 
	@LegacyDarthVaderAsia = 0x0DD2, // Value: 3538, Comment: 
	@DescentMk2s = 0x0DD6, // Value: 3542, Comment: 
	@Edge130Plus = 0x0DE6, // Value: 3558, Comment: 
	@Edge1030Plus = 0x0DF2, // Value: 3570, Comment: 
	@Rally200 = 0x0DFA, // Value: 3578, Comment: 
	@Fr745 = 0x0E05, // Value: 3589, Comment: 
	@Venusq = 0x0E10, // Value: 3600, Comment: 
	@Lily = 0x0E1F, // Value: 3615, Comment: 
	@MarqAdventurer = 0x0E28, // Value: 3624, Comment: 
	@Enduro = 0x0E36, // Value: 3638, Comment: 
	@Swim2Apac = 0x0E37, // Value: 3639, Comment: 
	@MarqAdventurerAsia = 0x0E40, // Value: 3648, Comment: 
	@Fr945Lte = 0x0E44, // Value: 3652, Comment: 
	@DescentMk2Asia = 0x0E76, // Value: 3702, Comment: 
	@Venu2 = 0x0E77, // Value: 3703, Comment: 
	@Venu2s = 0x0E78, // Value: 3704, Comment: 
	@VenuDaimlerAsia = 0x0E99, // Value: 3737, Comment: 
	@MarqGolfer = 0x0E9B, // Value: 3739, Comment: 
	@VenuDaimler = 0x0E9C, // Value: 3740, Comment: 
	@Fr745Asia = 0x0ED2, // Value: 3794, Comment: 
	@VariaRct715 = 0x0EE0, // Value: 3808, Comment: 
	@LilyAsia = 0x0EE1, // Value: 3809, Comment: 
	@Edge1030PlusAsia = 0x0EE4, // Value: 3812, Comment: 
	@Edge130PlusAsia = 0x0EE5, // Value: 3813, Comment: 
	@ApproachS12 = 0x0EEF, // Value: 3823, Comment: 
	@EnduroAsia = 0x0F20, // Value: 3872, Comment: 
	@VenusqAsia = 0x0EFD, // Value: 3837, Comment: 
	@Edge1040 = 0x0F03, // Value: 3843, Comment: 
	@MarqGolferAsia = 0x0F0A, // Value: 3850, Comment: 
	@Venu2Plus = 0x0F0B, // Value: 3851, Comment: 
	@Gnss = 0x0F19, // Value: 3865, Comment: 
	@Fr55 = 0x0F1D, // Value: 3869, Comment: 
	@Instinct2 = 0x0F30, // Value: 3888, Comment: 
	@Fenix7s = 0x0F41, // Value: 3905, Comment: 
	@Fenix7 = 0x0F42, // Value: 3906, Comment: 
	@Fenix7x = 0x0F43, // Value: 3907, Comment: 
	@Fenix7sApac = 0x0F44, // Value: 3908, Comment: 
	@Fenix7Apac = 0x0F45, // Value: 3909, Comment: 
	@Fenix7xApac = 0x0F46, // Value: 3910, Comment: 
	@ApproachG12 = 0x0F57, // Value: 3927, Comment: 
	@DescentMk2sAsia = 0x0F5A, // Value: 3930, Comment: 
	@ApproachS42 = 0x0F5E, // Value: 3934, Comment: 
	@EpixGen2 = 0x0F67, // Value: 3943, Comment: 
	@EpixGen2Apac = 0x0F68, // Value: 3944, Comment: 
	@Venu2sAsia = 0x0F6D, // Value: 3949, Comment: 
	@Venu2Asia = 0x0F6E, // Value: 3950, Comment: 
	@Fr945LteAsia = 0x0F8A, // Value: 3978, Comment: 
	@VivoMoveSport = 0x0F8E, // Value: 3982, Comment: 
	@VivomoveTrend = 0x0F8F, // Value: 3983, Comment: 
	@ApproachS12Asia = 0x0F92, // Value: 3986, Comment: 
	@Fr255Music = 0x0F96, // Value: 3990, Comment: 
	@Fr255SmallMusic = 0x0F97, // Value: 3991, Comment: 
	@Fr255 = 0x0F98, // Value: 3992, Comment: 
	@Fr255Small = 0x0F99, // Value: 3993, Comment: 
	@ApproachG12Asia = 0x0FA1, // Value: 4001, Comment: 
	@ApproachS42Asia = 0x0FA2, // Value: 4002, Comment: 
	@DescentG1 = 0x0FA5, // Value: 4005, Comment: 
	@Venu2PlusAsia = 0x0FB1, // Value: 4017, Comment: 
	@Fr955 = 0x0FB8, // Value: 4024, Comment: 
	@Fr55Asia = 0x0FC1, // Value: 4033, Comment: 
	@Edge540 = 0x0FDD, // Value: 4061, Comment: 
	@Edge840 = 0x0FDE, // Value: 4062, Comment: 
	@Vivosmart5 = 0x0FDF, // Value: 4063, Comment: 
	@Instinct2Asia = 0x0FE7, // Value: 4071, Comment: 
	@MarqGen2 = 0x1009, // Value: 4105, Comment: 
	@Venusq2 = 0x1013, // Value: 4115, Comment: 
	@Venusq2music = 0x1014, // Value: 4116, Comment: 
	@MarqGen2Aviator = 0x101C, // Value: 4124, Comment: 
	@D2AirX10 = 0x101D, // Value: 4125, Comment: 
	@HrmProPlus = 0x1022, // Value: 4130, Comment: 
	@DescentG1Asia = 0x1024, // Value: 4132, Comment: 
	@Tactix7 = 0x1027, // Value: 4135, Comment: 
	@InstinctCrossover = 0x103B, // Value: 4155, Comment: 
	@EdgeExplore2 = 0x1049, // Value: 4169, Comment: 
	@DescentMk3 = 0x107E, // Value: 4222, Comment: 
	@DescentMk3i = 0x107F, // Value: 4223, Comment: 
	@ApproachS70 = 0x1089, // Value: 4233, Comment: 
	@Fr265Large = 0x10A1, // Value: 4257, Comment: 
	@Fr265Small = 0x10A2, // Value: 4258, Comment: 
	@Venu3 = 0x10A4, // Value: 4260, Comment: 
	@Venu3s = 0x10A5, // Value: 4261, Comment: 
	@TacxNeoSmart = 0x10A9, // Value: 4265, Comment: 
	@TacxNeo2Smart = 0x10AA, // Value: 4266, Comment: 
	@TacxNeo2TSmart = 0x10AB, // Value: 4267, Comment: 
	@TacxNeoSmartBike = 0x10AC, // Value: 4268, Comment: 
	@TacxSatoriSmart = 0x10AD, // Value: 4269, Comment: 
	@TacxFlowSmart = 0x10AE, // Value: 4270, Comment: 
	@TacxVortexSmart = 0x10AF, // Value: 4271, Comment: 
	@TacxBushidoSmart = 0x10B0, // Value: 4272, Comment: 
	@TacxGeniusSmart = 0x10B1, // Value: 4273, Comment: 
	@TacxFluxFluxSSmart = 0x10B2, // Value: 4274, Comment: 
	@TacxFlux2Smart = 0x10B3, // Value: 4275, Comment: 
	@TacxMagnum = 0x10B4, // Value: 4276, Comment: 
	@Edge1040Asia = 0x10D1, // Value: 4305, Comment: 
	@EpixGen2Pro42 = 0x10D8, // Value: 4312, Comment: 
	@EpixGen2Pro47 = 0x10D9, // Value: 4313, Comment: 
	@EpixGen2Pro51 = 0x10DA, // Value: 4314, Comment: 
	@Fr965 = 0x10DB, // Value: 4315, Comment: 
	@Enduro2 = 0x10F5, // Value: 4341, Comment: 
	@Fenix7sProSolar = 0x1116, // Value: 4374, Comment: 
	@Fenix7ProSolar = 0x1117, // Value: 4375, Comment: 
	@Fenix7xProSolar = 0x1118, // Value: 4376, Comment: 
	@Lily2 = 0x111C, // Value: 4380, Comment: 
	@Instinct2x = 0x112A, // Value: 4394, Comment: 
	@Vivoactive5 = 0x114A, // Value: 4426, Comment: 
	@Fr165 = 0x1150, // Value: 4432, Comment: 
	@Fr165Music = 0x1151, // Value: 4433, Comment: 
	@Edge1050 = 0x1158, // Value: 4440, Comment: 
	@DescentT2 = 0x115A, // Value: 4442, Comment: 
	@HrmFit = 0x115E, // Value: 4446, Comment: 
	@MarqGen2Commander = 0x1178, // Value: 4472, Comment: 
	@LilyAthlete = 0x117D, // Value: 4477, Comment: 
	@Fenix8Solar = 0x11B4, // Value: 4532, Comment: 
	@Fenix8SolarLarge = 0x11B5, // Value: 4533, Comment: 
	@Fenix8Small = 0x11B6, // Value: 4534, Comment: 
	@Fenix8 = 0x11B8, // Value: 4536, Comment: 
	@D2Mach1Pro = 0x11CC, // Value: 4556, Comment: 
	@Enduro3 = 0x11DF, // Value: 4575, Comment: 
	@FenixE = 0x123A, // Value: 4666, Comment: 
	@Sdm4 = 0x2717, // Value: 10007, Comment: 
	@EdgeRemote = 0x271E, // Value: 10014, Comment: 
	@TacxTrainingAppWin = 0x5035, // Value: 20533, Comment: 
	@TacxTrainingAppMac = 0x5036, // Value: 20534, Comment: 
	@TacxTrainingAppMacCatalyst = 0x5055, // Value: 20565, Comment: 
	@TrainingCenter = 0x4E97, // Value: 20119, Comment: 
	@TacxTrainingAppAndroid = 0x755D, // Value: 30045, Comment: 
	@TacxTrainingAppIos = 0x755E, // Value: 30046, Comment: 
	@TacxTrainingAppLegacy = 0x755F, // Value: 30047, Comment: 
	@ConnectiqSimulator = 0xFFFB, // Value: 65531, Comment: 
	@AndroidAntplusPlugin = 0xFFFC, // Value: 65532, Comment: 
	@Connect = 0xFFFE // Value: 65534, Comment: 
};
