#include "fitTypeDecls.idl"

enum<byte,0xFF> HrZoneCalc
{
	@Custom = 0x00, // Value: 0, Comment: 
	@PercentMaxHr = 0x01, // Value: 1, Comment: 
	@PercentHrr = 0x02, // Value: 2, Comment: 
	@PercentLthr = 0x03 // Value: 3, Comment: 
};
