#include "fitTypeDecls.idl"

enum<uint16,0xFFFF> HyperextensionExerciseName
{
	@BackExtensionWithOppositeArmAndLegReach = 0x0000, // Value: 0, Comment: 
	@WeightedBackExtensionWithOppositeArmAndLegReach = 0x0001, // Value: 1, Comment: 
	@BaseRotations = 0x0002, // Value: 2, Comment: 
	@WeightedBaseRotations = 0x0003, // Value: 3, Comment: 
	@BentKneeReverseHyperextension = 0x0004, // Value: 4, Comment: 
	@WeightedBentKneeReverseHyperextension = 0x0005, // Value: 5, Comment: 
	@HollowHoldAndRoll = 0x0006, // Value: 6, Comment: 
	@WeightedHollowHoldAndRoll = 0x0007, // Value: 7, Comment: 
	@Kicks = 0x0008, // Value: 8, Comment: 
	@WeightedKicks = 0x0009, // Value: 9, Comment: 
	@KneeRaises = 0x000A, // Value: 10, Comment: 
	@WeightedKneeRaises = 0x000B, // Value: 11, Comment: 
	@KneelingSuperman = 0x000C, // Value: 12, Comment: 
	@WeightedKneelingSuperman = 0x000D, // Value: 13, Comment: 
	@LatPullDownWithRow = 0x000E, // Value: 14, Comment: 
	@MedicineBallDeadliftToReach = 0x000F, // Value: 15, Comment: 
	@OneArmOneLegRow = 0x0010, // Value: 16, Comment: 
	@OneArmRowWithBand = 0x0011, // Value: 17, Comment: 
	@OverheadLungeWithMedicineBall = 0x0012, // Value: 18, Comment: 
	@PlankKneeTucks = 0x0013, // Value: 19, Comment: 
	@WeightedPlankKneeTucks = 0x0014, // Value: 20, Comment: 
	@SideStep = 0x0015, // Value: 21, Comment: 
	@WeightedSideStep = 0x0016, // Value: 22, Comment: 
	@SingleLegBackExtension = 0x0017, // Value: 23, Comment: 
	@WeightedSingleLegBackExtension = 0x0018, // Value: 24, Comment: 
	@SpineExtension = 0x0019, // Value: 25, Comment: 
	@WeightedSpineExtension = 0x001A, // Value: 26, Comment: 
	@StaticBackExtension = 0x001B, // Value: 27, Comment: 
	@WeightedStaticBackExtension = 0x001C, // Value: 28, Comment: 
	@SupermanFromFloor = 0x001D, // Value: 29, Comment: 
	@WeightedSupermanFromFloor = 0x001E, // Value: 30, Comment: 
	@SwissBallBackExtension = 0x001F, // Value: 31, Comment: 
	@WeightedSwissBallBackExtension = 0x0020, // Value: 32, Comment: 
	@SwissBallHyperextension = 0x0021, // Value: 33, Comment: 
	@WeightedSwissBallHyperextension = 0x0022, // Value: 34, Comment: 
	@SwissBallOppositeArmAndLegLift = 0x0023, // Value: 35, Comment: 
	@WeightedSwissBallOppositeArmAndLegLift = 0x0024, // Value: 36, Comment: 
	@SupermanOnSwissBall = 0x0025, // Value: 37, Comment: 
	@Cobra = 0x0026 // Value: 38, Comment: 
};
