#include "fitTypeDecls.idl"

enum<byte,0xFF> Intensity
{
	@Active = 0x00, // Value: 0, Comment: 
	@Rest = 0x01, // Value: 1, Comment: 
	@Warmup = 0x02, // Value: 2, Comment: 
	@Cooldown = 0x03, // Value: 3, Comment: 
	@Recovery = 0x04, // Value: 4, Comment: 
	@Interval = 0x05, // Value: 5, Comment: 
	@Other = 0x06 // Value: 6, Comment: 
};
