#include "fitTypeDecls.idl"

enum<uint8,0x00> LanguageBits2
{
	@Slovenian = 0x01, // Value: 1, Comment: 
	@Swedish = 0x02, // Value: 2, Comment: 
	@Russian = 0x04, // Value: 4, Comment: 
	@Turkish = 0x08, // Value: 8, Comment: 
	@Latvian = 0x10, // Value: 16, Comment: 
	@Ukrainian = 0x20, // Value: 32, Comment: 
	@Arabic = 0x40, // Value: 64, Comment: 
	@Farsi = 0x80 // Value: 128, Comment: 
};
