#include "fitTypeDecls.idl"

enum<uint16,0xFFFF> MesgNum
{
	@FileId = 0x0000, // Value: 0, Comment: 
	@Capabilities = 0x0001, // Value: 1, Comment: 
	@DeviceSettings = 0x0002, // Value: 2, Comment: 
	@UserProfile = 0x0003, // Value: 3, Comment: 
	@HrmProfile = 0x0004, // Value: 4, Comment: 
	@SdmProfile = 0x0005, // Value: 5, Comment: 
	@BikeProfile = 0x0006, // Value: 6, Comment: 
	@ZonesTarget = 0x0007, // Value: 7, Comment: 
	@HrZone = 0x0008, // Value: 8, Comment: 
	@PowerZone = 0x0009, // Value: 9, Comment: 
	@MetZone = 0x000A, // Value: 10, Comment: 
	@Sport = 0x000C, // Value: 12, Comment: 
	@Goal = 0x000F, // Value: 15, Comment: 
	@Session = 0x0012, // Value: 18, Comment: 
	@Lap = 0x0013, // Value: 19, Comment: 
	@Record = 0x0014, // Value: 20, Comment: 
	@Event = 0x0015, // Value: 21, Comment: 
	@DeviceInfo = 0x0017, // Value: 23, Comment: 
	@Workout = 0x001A, // Value: 26, Comment: 
	@WorkoutStep = 0x001B, // Value: 27, Comment: 
	@Schedule = 0x001C, // Value: 28, Comment: 
	@WeightScale = 0x001E, // Value: 30, Comment: 
	@Course = 0x001F, // Value: 31, Comment: 
	@CoursePoint = 0x0020, // Value: 32, Comment: 
	@Totals = 0x0021, // Value: 33, Comment: 
	@Activity = 0x0022, // Value: 34, Comment: 
	@Software = 0x0023, // Value: 35, Comment: 
	@FileCapabilities = 0x0025, // Value: 37, Comment: 
	@MesgCapabilities = 0x0026, // Value: 38, Comment: 
	@FieldCapabilities = 0x0027, // Value: 39, Comment: 
	@FileCreator = 0x0031, // Value: 49, Comment: 
	@BloodPressure = 0x0033, // Value: 51, Comment: 
	@SpeedZone = 0x0035, // Value: 53, Comment: 
	@Monitoring = 0x0037, // Value: 55, Comment: 
	@TrainingFile = 0x0048, // Value: 72, Comment: 
	@Hrv = 0x004E, // Value: 78, Comment: 
	@AntRx = 0x0050, // Value: 80, Comment: 
	@AntTx = 0x0051, // Value: 81, Comment: 
	@AntChannelId = 0x0052, // Value: 82, Comment: 
	@Length = 0x0065, // Value: 101, Comment: 
	@MonitoringInfo = 0x0067, // Value: 103, Comment: 
	@Pad = 0x0069, // Value: 105, Comment: 
	@SlaveDevice = 0x006A, // Value: 106, Comment: 
	@Connectivity = 0x007F, // Value: 127, Comment: 
	@WeatherConditions = 0x0080, // Value: 128, Comment: 
	@WeatherAlert = 0x0081, // Value: 129, Comment: 
	@CadenceZone = 0x0083, // Value: 131, Comment: 
	@Hr = 0x0084, // Value: 132, Comment: 
	@SegmentLap = 0x008E, // Value: 142, Comment: 
	@MemoGlob = 0x0091, // Value: 145, Comment: 
	@SegmentId = 0x0094, // Value: 148, Comment: 
	@SegmentLeaderboardEntry = 0x0095, // Value: 149, Comment: 
	@SegmentPoint = 0x0096, // Value: 150, Comment: 
	@SegmentFile = 0x0097, // Value: 151, Comment: 
	@WorkoutSession = 0x009E, // Value: 158, Comment: 
	@WatchfaceSettings = 0x009F, // Value: 159, Comment: 
	@GpsMetadata = 0x00A0, // Value: 160, Comment: 
	@CameraEvent = 0x00A1, // Value: 161, Comment: 
	@TimestampCorrelation = 0x00A2, // Value: 162, Comment: 
	@GyroscopeData = 0x00A4, // Value: 164, Comment: 
	@AccelerometerData = 0x00A5, // Value: 165, Comment: 
	@ThreeDSensorCalibration = 0x00A7, // Value: 167, Comment: 
	@VideoFrame = 0x00A9, // Value: 169, Comment: 
	@ObdiiData = 0x00AE, // Value: 174, Comment: 
	@NmeaSentence = 0x00B1, // Value: 177, Comment: 
	@AviationAttitude = 0x00B2, // Value: 178, Comment: 
	@Video = 0x00B8, // Value: 184, Comment: 
	@VideoTitle = 0x00B9, // Value: 185, Comment: 
	@VideoDescription = 0x00BA, // Value: 186, Comment: 
	@VideoClip = 0x00BB, // Value: 187, Comment: 
	@OhrSettings = 0x00BC, // Value: 188, Comment: 
	@ExdScreenConfiguration = 0x00C8, // Value: 200, Comment: 
	@ExdDataFieldConfiguration = 0x00C9, // Value: 201, Comment: 
	@ExdDataConceptConfiguration = 0x00CA, // Value: 202, Comment: 
	@FieldDescription = 0x00CE, // Value: 206, Comment: 
	@DeveloperDataId = 0x00CF, // Value: 207, Comment: 
	@MagnetometerData = 0x00D0, // Value: 208, Comment: 
	@BarometerData = 0x00D1, // Value: 209, Comment: 
	@OneDSensorCalibration = 0x00D2, // Value: 210, Comment: 
	@MonitoringHrData = 0x00D3, // Value: 211, Comment: 
	@TimeInZone = 0x00D8, // Value: 216, Comment: 
	@Set = 0x00E1, // Value: 225, Comment: 
	@StressLevel = 0x00E3, // Value: 227, Comment: 
	@MaxMetData = 0x00E5, // Value: 229, Comment: 
	@DiveSettings = 0x0102, // Value: 258, Comment: 
	@DiveGas = 0x0103, // Value: 259, Comment: 
	@DiveAlarm = 0x0106, // Value: 262, Comment: 
	@ExerciseTitle = 0x0108, // Value: 264, Comment: 
	@DiveSummary = 0x010C, // Value: 268, Comment: 
	@Spo2Data = 0x010D, // Value: 269, Comment: 
	@SleepLevel = 0x0113, // Value: 275, Comment: 
	@Jump = 0x011D, // Value: 285, Comment: 
	@AadAccelFeatures = 0x0121, // Value: 289, Comment: 
	@BeatIntervals = 0x0122, // Value: 290, Comment: 
	@RespirationRate = 0x0129, // Value: 297, Comment: 
	@HsaAccelerometerData = 0x012E, // Value: 302, Comment: 
	@HsaStepData = 0x0130, // Value: 304, Comment: 
	@HsaSpo2Data = 0x0131, // Value: 305, Comment: 
	@HsaStressData = 0x0132, // Value: 306, Comment: 
	@HsaRespirationData = 0x0133, // Value: 307, Comment: 
	@HsaHeartRateData = 0x0134, // Value: 308, Comment: 
	@Split = 0x0138, // Value: 312, Comment: 
	@SplitSummary = 0x0139, // Value: 313, Comment: 
	@HsaBodyBatteryData = 0x013A, // Value: 314, Comment: 
	@HsaEvent = 0x013B, // Value: 315, Comment: 
	@ClimbPro = 0x013D, // Value: 317, Comment: 
	@TankUpdate = 0x013F, // Value: 319, Comment: 
	@TankSummary = 0x0143, // Value: 323, Comment: 
	@SleepAssessment = 0x015A, // Value: 346, Comment: 
	@HrvStatusSummary = 0x0172, // Value: 370, Comment: 
	@HrvValue = 0x0173, // Value: 371, Comment: 
	@RawBbi = 0x0174, // Value: 372, Comment: 
	@DeviceAuxBatteryInfo = 0x0177, // Value: 375, Comment: 
	@HsaGyroscopeData = 0x0178, // Value: 376, Comment: 
	@ChronoShotSession = 0x0183, // Value: 387, Comment: 
	@ChronoShotData = 0x0184, // Value: 388, Comment: 
	@HsaConfigurationData = 0x0185, // Value: 389, Comment: 
	@DiveApneaAlarm = 0x0189, // Value: 393, Comment: 
	@SkinTempOvernight = 0x018E, // Value: 398, Comment: 
	@HsaWristTemperatureData = 0x0199, // Value: 409, Comment: 
	@MfgRangeMin = 0xFF00, // Value: 65280, Comment: 
	@MfgRangeMax = 0xFFFE // Value: 65534, Comment: 
};
