#include "fitTypeDecls.idl"

enum<uint16,0xFFFF> Manufacturer
{
	@Garmin = 0x0001, // Value: 1, Comment: 
	@GarminFr405Antfs = 0x0002, // Value: 2, Comment: 
	@Zephyr = 0x0003, // Value: 3, Comment: 
	@Dayton = 0x0004, // Value: 4, Comment: 
	@Idt = 0x0005, // Value: 5, Comment: 
	@Srm = 0x0006, // Value: 6, Comment: 
	@Quarq = 0x0007, // Value: 7, Comment: 
	@Ibike = 0x0008, // Value: 8, Comment: 
	@Saris = 0x0009, // Value: 9, Comment: 
	@SparkHk = 0x000A, // Value: 10, Comment: 
	@Tanita = 0x000B, // Value: 11, Comment: 
	@Echowell = 0x000C, // Value: 12, Comment: 
	@DynastreamOem = 0x000D, // Value: 13, Comment: 
	@Nautilus = 0x000E, // Value: 14, Comment: 
	@Dynastream = 0x000F, // Value: 15, Comment: 
	@Timex = 0x0010, // Value: 16, Comment: 
	@Metrigear = 0x0011, // Value: 17, Comment: 
	@Xelic = 0x0012, // Value: 18, Comment: 
	@Beurer = 0x0013, // Value: 19, Comment: 
	@Cardiosport = 0x0014, // Value: 20, Comment: 
	@AAndD = 0x0015, // Value: 21, Comment: 
	@Hmm = 0x0016, // Value: 22, Comment: 
	@Suunto = 0x0017, // Value: 23, Comment: 
	@ThitaElektronik = 0x0018, // Value: 24, Comment: 
	@Gpulse = 0x0019, // Value: 25, Comment: 
	@CleanMobile = 0x001A, // Value: 26, Comment: 
	@PedalBrain = 0x001B, // Value: 27, Comment: 
	@Peaksware = 0x001C, // Value: 28, Comment: 
	@Saxonar = 0x001D, // Value: 29, Comment: 
	@LemondFitness = 0x001E, // Value: 30, Comment: 
	@Dexcom = 0x001F, // Value: 31, Comment: 
	@WahooFitness = 0x0020, // Value: 32, Comment: 
	@OctaneFitness = 0x0021, // Value: 33, Comment: 
	@Archinoetics = 0x0022, // Value: 34, Comment: 
	@TheHurtBox = 0x0023, // Value: 35, Comment: 
	@CitizenSystems = 0x0024, // Value: 36, Comment: 
	@Magellan = 0x0025, // Value: 37, Comment: 
	@Osynce = 0x0026, // Value: 38, Comment: 
	@Holux = 0x0027, // Value: 39, Comment: 
	@Concept2 = 0x0028, // Value: 40, Comment: 
	@Shimano = 0x0029, // Value: 41, Comment: 
	@OneGiantLeap = 0x002A, // Value: 42, Comment: 
	@AceSensor = 0x002B, // Value: 43, Comment: 
	@BrimBrothers = 0x002C, // Value: 44, Comment: 
	@Xplova = 0x002D, // Value: 45, Comment: 
	@PerceptionDigital = 0x002E, // Value: 46, Comment: 
	@Bf1systems = 0x002F, // Value: 47, Comment: 
	@Pioneer = 0x0030, // Value: 48, Comment: 
	@Spantec = 0x0031, // Value: 49, Comment: 
	@Metalogics = 0x0032, // Value: 50, Comment: 
	@_4iiiis = 0x0033, // Value: 51, Comment: 
	@SeikoEpson = 0x0034, // Value: 52, Comment: 
	@SeikoEpsonOem = 0x0035, // Value: 53, Comment: 
	@IforPowell = 0x0036, // Value: 54, Comment: 
	@MaxwellGuider = 0x0037, // Value: 55, Comment: 
	@StarTrac = 0x0038, // Value: 56, Comment: 
	@Breakaway = 0x0039, // Value: 57, Comment: 
	@AlatechTechnologyLtd = 0x003A, // Value: 58, Comment: 
	@MioTechnologyEurope = 0x003B, // Value: 59, Comment: 
	@Rotor = 0x003C, // Value: 60, Comment: 
	@Geonaute = 0x003D, // Value: 61, Comment: 
	@IdBike = 0x003E, // Value: 62, Comment: 
	@Specialized = 0x003F, // Value: 63, Comment: 
	@Wtek = 0x0040, // Value: 64, Comment: 
	@PhysicalEnterprises = 0x0041, // Value: 65, Comment: 
	@NorthPoleEngineering = 0x0042, // Value: 66, Comment: 
	@Bkool = 0x0043, // Value: 67, Comment: 
	@Cateye = 0x0044, // Value: 68, Comment: 
	@StagesCycling = 0x0045, // Value: 69, Comment: 
	@Sigmasport = 0x0046, // Value: 70, Comment: 
	@Tomtom = 0x0047, // Value: 71, Comment: 
	@Peripedal = 0x0048, // Value: 72, Comment: 
	@Wattbike = 0x0049, // Value: 73, Comment: 
	@Moxy = 0x004C, // Value: 76, Comment: 
	@Ciclosport = 0x004D, // Value: 77, Comment: 
	@Powerbahn = 0x004E, // Value: 78, Comment: 
	@AcornProjectsAps = 0x004F, // Value: 79, Comment: 
	@Lifebeam = 0x0050, // Value: 80, Comment: 
	@Bontrager = 0x0051, // Value: 81, Comment: 
	@Wellgo = 0x0052, // Value: 82, Comment: 
	@Scosche = 0x0053, // Value: 83, Comment: 
	@Magura = 0x0054, // Value: 84, Comment: 
	@Woodway = 0x0055, // Value: 85, Comment: 
	@Elite = 0x0056, // Value: 86, Comment: 
	@NielsenKellerman = 0x0057, // Value: 87, Comment: 
	@DkCity = 0x0058, // Value: 88, Comment: 
	@Tacx = 0x0059, // Value: 89, Comment: 
	@DirectionTechnology = 0x005A, // Value: 90, Comment: 
	@Magtonic = 0x005B, // Value: 91, Comment: 
	@_1partcarbon = 0x005C, // Value: 92, Comment: 
	@InsideRideTechnologies = 0x005D, // Value: 93, Comment: 
	@SoundOfMotion = 0x005E, // Value: 94, Comment: 
	@Stryd = 0x005F, // Value: 95, Comment: 
	@Icg = 0x0060, // Value: 96, Comment: 
	@MiPulse = 0x0061, // Value: 97, Comment: 
	@BsxAthletics = 0x0062, // Value: 98, Comment: 
	@Look = 0x0063, // Value: 99, Comment: 
	@CampagnoloSrl = 0x0064, // Value: 100, Comment: 
	@BodyBikeSmart = 0x0065, // Value: 101, Comment: 
	@Praxisworks = 0x0066, // Value: 102, Comment: 
	@LimitsTechnology = 0x0067, // Value: 103, Comment: 
	@TopactionTechnology = 0x0068, // Value: 104, Comment: 
	@Cosinuss = 0x0069, // Value: 105, Comment: 
	@Fitcare = 0x006A, // Value: 106, Comment: 
	@Magene = 0x006B, // Value: 107, Comment: 
	@GiantManufacturingCo = 0x006C, // Value: 108, Comment: 
	@Tigrasport = 0x006D, // Value: 109, Comment: 
	@Salutron = 0x006E, // Value: 110, Comment: 
	@Technogym = 0x006F, // Value: 111, Comment: 
	@BrytonSensors = 0x0070, // Value: 112, Comment: 
	@LatitudeLimited = 0x0071, // Value: 113, Comment: 
	@SoaringTechnology = 0x0072, // Value: 114, Comment: 
	@Igpsport = 0x0073, // Value: 115, Comment: 
	@Thinkrider = 0x0074, // Value: 116, Comment: 
	@GopherSport = 0x0075, // Value: 117, Comment: 
	@Waterrower = 0x0076, // Value: 118, Comment: 
	@Orangetheory = 0x0077, // Value: 119, Comment: 
	@Inpeak = 0x0078, // Value: 120, Comment: 
	@Kinetic = 0x0079, // Value: 121, Comment: 
	@JohnsonHealthTech = 0x007A, // Value: 122, Comment: 
	@PolarElectro = 0x007B, // Value: 123, Comment: 
	@Seesense = 0x007C, // Value: 124, Comment: 
	@NciTechnology = 0x007D, // Value: 125, Comment: 
	@Iqsquare = 0x007E, // Value: 126, Comment: 
	@Leomo = 0x007F, // Value: 127, Comment: 
	@IfitCom = 0x0080, // Value: 128, Comment: 
	@CorosByte = 0x0081, // Value: 129, Comment: 
	@VersaDesign = 0x0082, // Value: 130, Comment: 
	@Chileaf = 0x0083, // Value: 131, Comment: 
	@Cycplus = 0x0084, // Value: 132, Comment: 
	@GravaaByte = 0x0085, // Value: 133, Comment: 
	@Sigeyi = 0x0086, // Value: 134, Comment: 
	@Coospo = 0x0087, // Value: 135, Comment: 
	@Geoid = 0x0088, // Value: 136, Comment: 
	@Bosch = 0x0089, // Value: 137, Comment: 
	@Kyto = 0x008A, // Value: 138, Comment: 
	@KineticSports = 0x008B, // Value: 139, Comment: 
	@DecathlonByte = 0x008C, // Value: 140, Comment: 
	@TqSystems = 0x008D, // Value: 141, Comment: 
	@TagHeuer = 0x008E, // Value: 142, Comment: 
	@KeiserFitness = 0x008F, // Value: 143, Comment: 
	@ZwiftByte = 0x0090, // Value: 144, Comment: 
	@PorscheEp = 0x0091, // Value: 145, Comment: 
	@Blackbird = 0x0092, // Value: 146, Comment: 
	@MeilanByte = 0x0093, // Value: 147, Comment: 
	@Ezon = 0x0094, // Value: 148, Comment: 
	@Laisi = 0x0095, // Value: 149, Comment: 
	@Myzone = 0x0096, // Value: 150, Comment: 
	@Abawo = 0x0097, // Value: 151, Comment: 
	@Bafang = 0x0098, // Value: 152, Comment: 
	@Development = 0x00FF, // Value: 255, Comment: 
	@Healthandlife = 0x0101, // Value: 257, Comment: 
	@Lezyne = 0x0102, // Value: 258, Comment: 
	@ScribeLabs = 0x0103, // Value: 259, Comment: 
	@Zwift = 0x0104, // Value: 260, Comment: 
	@Watteam = 0x0105, // Value: 261, Comment: 
	@Recon = 0x0106, // Value: 262, Comment: 
	@FaveroElectronics = 0x0107, // Value: 263, Comment: 
	@Dynovelo = 0x0108, // Value: 264, Comment: 
	@Strava = 0x0109, // Value: 265, Comment: 
	@Precor = 0x010A, // Value: 266, Comment: 
	@Bryton = 0x010B, // Value: 267, Comment: 
	@Sram = 0x010C, // Value: 268, Comment: 
	@Navman = 0x010D, // Value: 269, Comment: 
	@Cobi = 0x010E, // Value: 270, Comment: 
	@Spivi = 0x010F, // Value: 271, Comment: 
	@MioMagellan = 0x0110, // Value: 272, Comment: 
	@Evesports = 0x0111, // Value: 273, Comment: 
	@SensitivusGauge = 0x0112, // Value: 274, Comment: 
	@Podoon = 0x0113, // Value: 275, Comment: 
	@LifeTimeFitness = 0x0114, // Value: 276, Comment: 
	@FalcoEMotors = 0x0115, // Value: 277, Comment: 
	@Minoura = 0x0116, // Value: 278, Comment: 
	@Cycliq = 0x0117, // Value: 279, Comment: 
	@Luxottica = 0x0118, // Value: 280, Comment: 
	@TrainerRoad = 0x0119, // Value: 281, Comment: 
	@TheSufferfest = 0x011A, // Value: 282, Comment: 
	@Fullspeedahead = 0x011B, // Value: 283, Comment: 
	@Virtualtraining = 0x011C, // Value: 284, Comment: 
	@Feedbacksports = 0x011D, // Value: 285, Comment: 
	@Omata = 0x011E, // Value: 286, Comment: 
	@Vdo = 0x011F, // Value: 287, Comment: 
	@Magneticdays = 0x0120, // Value: 288, Comment: 
	@Hammerhead = 0x0121, // Value: 289, Comment: 
	@KineticByKurt = 0x0122, // Value: 290, Comment: 
	@Shapelog = 0x0123, // Value: 291, Comment: 
	@Dabuziduo = 0x0124, // Value: 292, Comment: 
	@Jetblack = 0x0125, // Value: 293, Comment: 
	@Coros = 0x0126, // Value: 294, Comment: 
	@Virtugo = 0x0127, // Value: 295, Comment: 
	@Velosense = 0x0128, // Value: 296, Comment: 
	@Cycligentinc = 0x0129, // Value: 297, Comment: 
	@Trailforks = 0x012A, // Value: 298, Comment: 
	@MahleEbikemotion = 0x012B, // Value: 299, Comment: 
	@Nurvv = 0x012C, // Value: 300, Comment: 
	@Microprogram = 0x012D, // Value: 301, Comment: 
	@Zone5cloud = 0x012E, // Value: 302, Comment: 
	@Greenteg = 0x012F, // Value: 303, Comment: 
	@YamahaMotors = 0x0130, // Value: 304, Comment: 
	@Whoop = 0x0131, // Value: 305, Comment: 
	@Gravaa = 0x0132, // Value: 306, Comment: 
	@Onelap = 0x0133, // Value: 307, Comment: 
	@MonarkExercise = 0x0134, // Value: 308, Comment: 
	@Form = 0x0135, // Value: 309, Comment: 
	@Decathlon = 0x0136, // Value: 310, Comment: 
	@Syncros = 0x0137, // Value: 311, Comment: 
	@Heatup = 0x0138, // Value: 312, Comment: 
	@Cannondale = 0x0139, // Value: 313, Comment: 
	@TrueFitness = 0x013A, // Value: 314, Comment: 
	@RGTCycling = 0x013B, // Value: 315, Comment: 
	@Vasa = 0x013C, // Value: 316, Comment: 
	@RaceRepublic = 0x013D, // Value: 317, Comment: 
	@Fazua = 0x013E, // Value: 318, Comment: 
	@OrekaTraining = 0x013F, // Value: 319, Comment: 
	@Lsec = 0x0140, // Value: 320, Comment: 
	@LululemonStudio = 0x0141, // Value: 321, Comment: 
	@Shanyue = 0x0142, // Value: 322, Comment: 
	@SpinningMda = 0x0143, // Value: 323, Comment: 
	@Hilldating = 0x0144, // Value: 324, Comment: 
	@AeroSensor = 0x0145, // Value: 325, Comment: 
	@Nike = 0x0146, // Value: 326, Comment: 
	@Magicshine = 0x0147, // Value: 327, Comment: 
	@Ictrainer = 0x0148, // Value: 328, Comment: 
	@AbsoluteCycling = 0x0149, // Value: 329, Comment: 
	@EoSwimbetter = 0x014A, // Value: 330, Comment: 
	@Mywhoosh = 0x014B, // Value: 331, Comment: 
	@Ravemen = 0x014C, // Value: 332, Comment: 
	@Actigraphcorp = 0x167F // Value: 5759, Comment: 
};
