#include "fitTypeDecls.idl"

enum<byte,0xFF> PowerPhaseType
{
	@PowerPhaseStartAngle = 0x00, // Value: 0, Comment: 
	@PowerPhaseEndAngle = 0x01, // Value: 1, Comment: 
	@PowerPhaseArcLength = 0x02, // Value: 2, Comment: 
	@PowerPhaseCenter = 0x03 // Value: 3, Comment: 
};
