#include "fitTypeDecls.idl"

enum<uint16,0xFFFF> PlankExerciseName
{
	@_45DegreePlank = 0x0000, // Value: 0, Comment: 
	@Weighted45DegreePlank = 0x0001, // Value: 1, Comment: 
	@_90DegreeStaticHold = 0x0002, // Value: 2, Comment: 
	@Weighted90DegreeStaticHold = 0x0003, // Value: 3, Comment: 
	@BearCrawl = 0x0004, // Value: 4, Comment: 
	@WeightedBearCrawl = 0x0005, // Value: 5, Comment: 
	@CrossBodyMountainClimber = 0x0006, // Value: 6, Comment: 
	@WeightedCrossBodyMountainClimber = 0x0007, // Value: 7, Comment: 
	@ElbowPlankPikeJacks = 0x0008, // Value: 8, Comment: 
	@WeightedElbowPlankPikeJacks = 0x0009, // Value: 9, Comment: 
	@ElevatedFeetPlank = 0x000A, // Value: 10, Comment: 
	@WeightedElevatedFeetPlank = 0x000B, // Value: 11, Comment: 
	@ElevatorAbs = 0x000C, // Value: 12, Comment: 
	@WeightedElevatorAbs = 0x000D, // Value: 13, Comment: 
	@ExtendedPlank = 0x000E, // Value: 14, Comment: 
	@WeightedExtendedPlank = 0x000F, // Value: 15, Comment: 
	@FullPlankPasseTwist = 0x0010, // Value: 16, Comment: 
	@WeightedFullPlankPasseTwist = 0x0011, // Value: 17, Comment: 
	@InchingElbowPlank = 0x0012, // Value: 18, Comment: 
	@WeightedInchingElbowPlank = 0x0013, // Value: 19, Comment: 
	@InchwormToSidePlank = 0x0014, // Value: 20, Comment: 
	@WeightedInchwormToSidePlank = 0x0015, // Value: 21, Comment: 
	@KneelingPlank = 0x0016, // Value: 22, Comment: 
	@WeightedKneelingPlank = 0x0017, // Value: 23, Comment: 
	@KneelingSidePlankWithLegLift = 0x0018, // Value: 24, Comment: 
	@WeightedKneelingSidePlankWithLegLift = 0x0019, // Value: 25, Comment: 
	@LateralRoll = 0x001A, // Value: 26, Comment: 
	@WeightedLateralRoll = 0x001B, // Value: 27, Comment: 
	@LyingReversePlank = 0x001C, // Value: 28, Comment: 
	@WeightedLyingReversePlank = 0x001D, // Value: 29, Comment: 
	@MedicineBallMountainClimber = 0x001E, // Value: 30, Comment: 
	@WeightedMedicineBallMountainClimber = 0x001F, // Value: 31, Comment: 
	@ModifiedMountainClimberAndExtension = 0x0020, // Value: 32, Comment: 
	@WeightedModifiedMountainClimberAndExtension = 0x0021, // Value: 33, Comment: 
	@MountainClimber = 0x0022, // Value: 34, Comment: 
	@WeightedMountainClimber = 0x0023, // Value: 35, Comment: 
	@MountainClimberOnSlidingDiscs = 0x0024, // Value: 36, Comment: 
	@WeightedMountainClimberOnSlidingDiscs = 0x0025, // Value: 37, Comment: 
	@MountainClimberWithFeetOnBosuBall = 0x0026, // Value: 38, Comment: 
	@WeightedMountainClimberWithFeetOnBosuBall = 0x0027, // Value: 39, Comment: 
	@MountainClimberWithHandsOnBench = 0x0028, // Value: 40, Comment: 
	@MountainClimberWithHandsOnSwissBall = 0x0029, // Value: 41, Comment: 
	@WeightedMountainClimberWithHandsOnSwissBall = 0x002A, // Value: 42, Comment: 
	@Plank = 0x002B, // Value: 43, Comment: 
	@PlankJacksWithFeetOnSlidingDiscs = 0x002C, // Value: 44, Comment: 
	@WeightedPlankJacksWithFeetOnSlidingDiscs = 0x002D, // Value: 45, Comment: 
	@PlankKneeTwist = 0x002E, // Value: 46, Comment: 
	@WeightedPlankKneeTwist = 0x002F, // Value: 47, Comment: 
	@PlankPikeJumps = 0x0030, // Value: 48, Comment: 
	@WeightedPlankPikeJumps = 0x0031, // Value: 49, Comment: 
	@PlankPikes = 0x0032, // Value: 50, Comment: 
	@WeightedPlankPikes = 0x0033, // Value: 51, Comment: 
	@PlankToStandUp = 0x0034, // Value: 52, Comment: 
	@WeightedPlankToStandUp = 0x0035, // Value: 53, Comment: 
	@PlankWithArmRaise = 0x0036, // Value: 54, Comment: 
	@WeightedPlankWithArmRaise = 0x0037, // Value: 55, Comment: 
	@PlankWithKneeToElbow = 0x0038, // Value: 56, Comment: 
	@WeightedPlankWithKneeToElbow = 0x0039, // Value: 57, Comment: 
	@PlankWithObliqueCrunch = 0x003A, // Value: 58, Comment: 
	@WeightedPlankWithObliqueCrunch = 0x003B, // Value: 59, Comment: 
	@PlyometricSidePlank = 0x003C, // Value: 60, Comment: 
	@WeightedPlyometricSidePlank = 0x003D, // Value: 61, Comment: 
	@RollingSidePlank = 0x003E, // Value: 62, Comment: 
	@WeightedRollingSidePlank = 0x003F, // Value: 63, Comment: 
	@SideKickPlank = 0x0040, // Value: 64, Comment: 
	@WeightedSideKickPlank = 0x0041, // Value: 65, Comment: 
	@SidePlank = 0x0042, // Value: 66, Comment: 
	@WeightedSidePlank = 0x0043, // Value: 67, Comment: 
	@SidePlankAndRow = 0x0044, // Value: 68, Comment: 
	@WeightedSidePlankAndRow = 0x0045, // Value: 69, Comment: 
	@SidePlankLift = 0x0046, // Value: 70, Comment: 
	@WeightedSidePlankLift = 0x0047, // Value: 71, Comment: 
	@SidePlankWithElbowOnBosuBall = 0x0048, // Value: 72, Comment: 
	@WeightedSidePlankWithElbowOnBosuBall = 0x0049, // Value: 73, Comment: 
	@SidePlankWithFeetOnBench = 0x004A, // Value: 74, Comment: 
	@WeightedSidePlankWithFeetOnBench = 0x004B, // Value: 75, Comment: 
	@SidePlankWithKneeCircle = 0x004C, // Value: 76, Comment: 
	@WeightedSidePlankWithKneeCircle = 0x004D, // Value: 77, Comment: 
	@SidePlankWithKneeTuck = 0x004E, // Value: 78, Comment: 
	@WeightedSidePlankWithKneeTuck = 0x004F, // Value: 79, Comment: 
	@SidePlankWithLegLift = 0x0050, // Value: 80, Comment: 
	@WeightedSidePlankWithLegLift = 0x0051, // Value: 81, Comment: 
	@SidePlankWithReachUnder = 0x0052, // Value: 82, Comment: 
	@WeightedSidePlankWithReachUnder = 0x0053, // Value: 83, Comment: 
	@SingleLegElevatedFeetPlank = 0x0054, // Value: 84, Comment: 
	@WeightedSingleLegElevatedFeetPlank = 0x0055, // Value: 85, Comment: 
	@SingleLegFlexAndExtend = 0x0056, // Value: 86, Comment: 
	@WeightedSingleLegFlexAndExtend = 0x0057, // Value: 87, Comment: 
	@SingleLegSidePlank = 0x0058, // Value: 88, Comment: 
	@WeightedSingleLegSidePlank = 0x0059, // Value: 89, Comment: 
	@SpidermanPlank = 0x005A, // Value: 90, Comment: 
	@WeightedSpidermanPlank = 0x005B, // Value: 91, Comment: 
	@StraightArmPlank = 0x005C, // Value: 92, Comment: 
	@WeightedStraightArmPlank = 0x005D, // Value: 93, Comment: 
	@StraightArmPlankWithShoulderTouch = 0x005E, // Value: 94, Comment: 
	@WeightedStraightArmPlankWithShoulderTouch = 0x005F, // Value: 95, Comment: 
	@SwissBallPlank = 0x0060, // Value: 96, Comment: 
	@WeightedSwissBallPlank = 0x0061, // Value: 97, Comment: 
	@SwissBallPlankLegLift = 0x0062, // Value: 98, Comment: 
	@WeightedSwissBallPlankLegLift = 0x0063, // Value: 99, Comment: 
	@SwissBallPlankLegLiftAndHold = 0x0064, // Value: 100, Comment: 
	@SwissBallPlankWithFeetOnBench = 0x0065, // Value: 101, Comment: 
	@WeightedSwissBallPlankWithFeetOnBench = 0x0066, // Value: 102, Comment: 
	@SwissBallProneJackknife = 0x0067, // Value: 103, Comment: 
	@WeightedSwissBallProneJackknife = 0x0068, // Value: 104, Comment: 
	@SwissBallSidePlank = 0x0069, // Value: 105, Comment: 
	@WeightedSwissBallSidePlank = 0x006A, // Value: 106, Comment: 
	@ThreeWayPlank = 0x006B, // Value: 107, Comment: 
	@WeightedThreeWayPlank = 0x006C, // Value: 108, Comment: 
	@TowelPlankAndKneeIn = 0x006D, // Value: 109, Comment: 
	@WeightedTowelPlankAndKneeIn = 0x006E, // Value: 110, Comment: 
	@TStabilization = 0x006F, // Value: 111, Comment: 
	@WeightedTStabilization = 0x0070, // Value: 112, Comment: 
	@TurkishGetUpToSidePlank = 0x0071, // Value: 113, Comment: 
	@WeightedTurkishGetUpToSidePlank = 0x0072, // Value: 114, Comment: 
	@TwoPointPlank = 0x0073, // Value: 115, Comment: 
	@WeightedTwoPointPlank = 0x0074, // Value: 116, Comment: 
	@WeightedPlank = 0x0075, // Value: 117, Comment: 
	@WideStancePlankWithDiagonalArmLift = 0x0076, // Value: 118, Comment: 
	@WeightedWideStancePlankWithDiagonalArmLift = 0x0077, // Value: 119, Comment: 
	@WideStancePlankWithDiagonalLegLift = 0x0078, // Value: 120, Comment: 
	@WeightedWideStancePlankWithDiagonalLegLift = 0x0079, // Value: 121, Comment: 
	@WideStancePlankWithLegLift = 0x007A, // Value: 122, Comment: 
	@WeightedWideStancePlankWithLegLift = 0x007B, // Value: 123, Comment: 
	@WideStancePlankWithOppositeArmAndLegLift = 0x007C, // Value: 124, Comment: 
	@WeightedMountainClimberWithHandsOnBench = 0x007D, // Value: 125, Comment: 
	@WeightedSwissBallPlankLegLiftAndHold = 0x007E, // Value: 126, Comment: 
	@WeightedWideStancePlankWithOppositeArmAndLegLift = 0x007F, // Value: 127, Comment: 
	@PlankWithFeetOnSwissBall = 0x0080, // Value: 128, Comment: 
	@SidePlankToPlankWithReachUnder = 0x0081, // Value: 129, Comment: 
	@BridgeWithGluteLowerLift = 0x0082, // Value: 130, Comment: 
	@BridgeOneLegBridge = 0x0083, // Value: 131, Comment: 
	@PlankWithArmVariations = 0x0084, // Value: 132, Comment: 
	@PlankWithLegLift = 0x0085, // Value: 133, Comment: 
	@ReversePlankWithLegPull = 0x0086 // Value: 134, Comment: 
};
