#include "fitTypeDecls.idl"

enum<byte,0xFF> RadarThreatLevelType
{
	@ThreatUnknown = 0x00, // Value: 0, Comment: 
	@ThreatNone = 0x01, // Value: 1, Comment: 
	@ThreatApproaching = 0x02, // Value: 2, Comment: 
	@ThreatApproachingFast = 0x03 // Value: 3, Comment: 
};
