#include "fitTypeDecls.idl"

enum<byte,0xFF> SegmentDeleteStatus
{
	@DoNotDelete = 0x00, // Value: 0, Comment: 
	@DeleteOne = 0x01, // Value: 1, Comment: 
	@DeleteAll = 0x02 // Value: 2, Comment: 
};
