#include "fitTypeDecls.idl"

enum<byte,0xFF> SubSport
{
	@Generic = 0x00, // Value: 0, Comment: 
	@Treadmill = 0x01, // Value: 1, Comment: 
	@Street = 0x02, // Value: 2, Comment: 
	@Trail = 0x03, // Value: 3, Comment: 
	@Track = 0x04, // Value: 4, Comment: 
	@Spin = 0x05, // Value: 5, Comment: 
	@IndoorCycling = 0x06, // Value: 6, Comment: 
	@Road = 0x07, // Value: 7, Comment: 
	@Mountain = 0x08, // Value: 8, Comment: 
	@Downhill = 0x09, // Value: 9, Comment: 
	@Recumbent = 0x0A, // Value: 10, Comment: 
	@Cyclocross = 0x0B, // Value: 11, Comment: 
	@HandCycling = 0x0C, // Value: 12, Comment: 
	@TrackCycling = 0x0D, // Value: 13, Comment: 
	@IndoorRowing = 0x0E, // Value: 14, Comment: 
	@Elliptical = 0x0F, // Value: 15, Comment: 
	@StairClimbing = 0x10, // Value: 16, Comment: 
	@LapSwimming = 0x11, // Value: 17, Comment: 
	@OpenWater = 0x12, // Value: 18, Comment: 
	@FlexibilityTraining = 0x13, // Value: 19, Comment: 
	@StrengthTraining = 0x14, // Value: 20, Comment: 
	@WarmUp = 0x15, // Value: 21, Comment: 
	@Match = 0x16, // Value: 22, Comment: 
	@Exercise = 0x17, // Value: 23, Comment: 
	@Challenge = 0x18, // Value: 24, Comment: 
	@IndoorSkiing = 0x19, // Value: 25, Comment: 
	@CardioTraining = 0x1A, // Value: 26, Comment: 
	@IndoorWalking = 0x1B, // Value: 27, Comment: 
	@EBikeFitness = 0x1C, // Value: 28, Comment: 
	@Bmx = 0x1D, // Value: 29, Comment: 
	@CasualWalking = 0x1E, // Value: 30, Comment: 
	@SpeedWalking = 0x1F, // Value: 31, Comment: 
	@BikeToRunTransition = 0x20, // Value: 32, Comment: 
	@RunToBikeTransition = 0x21, // Value: 33, Comment: 
	@SwimToBikeTransition = 0x22, // Value: 34, Comment: 
	@Atv = 0x23, // Value: 35, Comment: 
	@Motocross = 0x24, // Value: 36, Comment: 
	@Backcountry = 0x25, // Value: 37, Comment: 
	@Resort = 0x26, // Value: 38, Comment: 
	@RcDrone = 0x27, // Value: 39, Comment: 
	@Wingsuit = 0x28, // Value: 40, Comment: 
	@Whitewater = 0x29, // Value: 41, Comment: 
	@SkateSkiing = 0x2A, // Value: 42, Comment: 
	@Yoga = 0x2B, // Value: 43, Comment: 
	@Pilates = 0x2C, // Value: 44, Comment: 
	@IndoorRunning = 0x2D, // Value: 45, Comment: 
	@GravelCycling = 0x2E, // Value: 46, Comment: 
	@EBikeMountain = 0x2F, // Value: 47, Comment: 
	@Commuting = 0x30, // Value: 48, Comment: 
	@MixedSurface = 0x31, // Value: 49, Comment: 
	@Navigate = 0x32, // Value: 50, Comment: 
	@TrackMe = 0x33, // Value: 51, Comment: 
	@Map = 0x34, // Value: 52, Comment: 
	@SingleGasDiving = 0x35, // Value: 53, Comment: 
	@MultiGasDiving = 0x36, // Value: 54, Comment: 
	@GaugeDiving = 0x37, // Value: 55, Comment: 
	@ApneaDiving = 0x38, // Value: 56, Comment: 
	@ApneaHunting = 0x39, // Value: 57, Comment: 
	@VirtualActivity = 0x3A, // Value: 58, Comment: 
	@Obstacle = 0x3B, // Value: 59, Comment: 
	@Breathing = 0x3E, // Value: 62, Comment: 
	@SailRace = 0x41, // Value: 65, Comment: 
	@Ultra = 0x43, // Value: 67, Comment: 
	@IndoorClimbing = 0x44, // Value: 68, Comment: 
	@Bouldering = 0x45, // Value: 69, Comment: 
	@Hiit = 0x46, // Value: 70, Comment: 
	@Amrap = 0x49, // Value: 73, Comment: 
	@Emom = 0x4A, // Value: 74, Comment: 
	@Tabata = 0x4B, // Value: 75, Comment: 
	@Pickleball = 0x54, // Value: 84, Comment: 
	@Padel = 0x55, // Value: 85, Comment: 
	@IndoorWheelchairWalk = 0x56, // Value: 86, Comment: 
	@IndoorWheelchairRun = 0x57, // Value: 87, Comment: 
	@IndoorHandCycling = 0x58, // Value: 88, Comment: 
	@Squash = 0x5E, // Value: 94, Comment: 
	@Badminton = 0x5F, // Value: 95, Comment: 
	@Racquetball = 0x60, // Value: 96, Comment: 
	@TableTennis = 0x61, // Value: 97, Comment: 
	@FlyCanopy = 0x6E, // Value: 110, Comment: 
	@FlyParaglide = 0x6F, // Value: 111, Comment: 
	@FlyParamotor = 0x70, // Value: 112, Comment: 
	@FlyPressurized = 0x71, // Value: 113, Comment: 
	@FlyNavigate = 0x72, // Value: 114, Comment: 
	@FlyTimer = 0x73, // Value: 115, Comment: 
	@FlyAltimeter = 0x74, // Value: 116, Comment: 
	@FlyWx = 0x75, // Value: 117, Comment: 
	@FlyVfr = 0x76, // Value: 118, Comment: 
	@FlyIfr = 0x77, // Value: 119, Comment: 
	@All = 0xFE // Value: 254, Comment: 
};
