#include "fitTypeDecls.idl"

enum<uint8,0x00> SportBits3
{
	@Driving = 0x01, // Value: 1, Comment: Bit field corresponding to sport enum type (1 << (sport-24)).
	@Golf = 0x02, // Value: 2, Comment: Bit field corresponding to sport enum type (1 << (sport-24)).
	@HangGliding = 0x04, // Value: 4, Comment: Bit field corresponding to sport enum type (1 << (sport-24)).
	@HorsebackRiding = 0x08, // Value: 8, Comment: Bit field corresponding to sport enum type (1 << (sport-24)).
	@Hunting = 0x10, // Value: 16, Comment: Bit field corresponding to sport enum type (1 << (sport-24)).
	@Fishing = 0x20, // Value: 32, Comment: Bit field corresponding to sport enum type (1 << (sport-24)).
	@InlineSkating = 0x40, // Value: 64, Comment: Bit field corresponding to sport enum type (1 << (sport-24)).
	@RockClimbing = 0x80 // Value: 128, Comment: Bit field corresponding to sport enum type (1 << (sport-24)).
};
