#include "fitTypeDecls.idl"
#include "fitAllTypes.idl"

struct<"SpeedZone", ""> SpeedZone {
	MessageIndex<"Enum", 254, -1, "", 1, 1, "", "", "", "", "", "", "", "1"> @MessageIndex;
	uint16<"Uint16", 0, -1, "", 1000, 1, "m/s", "", "", "", "", "", "", "1"> @HighValue;
	string<"String", 1, -1, "", 1, 1, "", "", "", "", "", "", "", "16"> @Name;
};
