#include "fitTypeDecls.idl"

enum<byte,0xFF> Sport
{
	@Generic = 0x00, // Value: 0, Comment: 
	@Running = 0x01, // Value: 1, Comment: 
	@Cycling = 0x02, // Value: 2, Comment: 
	@Transition = 0x03, // Value: 3, Comment: 
	@FitnessEquipment = 0x04, // Value: 4, Comment: 
	@Swimming = 0x05, // Value: 5, Comment: 
	@Basketball = 0x06, // Value: 6, Comment: 
	@Soccer = 0x07, // Value: 7, Comment: 
	@Tennis = 0x08, // Value: 8, Comment: 
	@AmericanFootball = 0x09, // Value: 9, Comment: 
	@Training = 0x0A, // Value: 10, Comment: 
	@Walking = 0x0B, // Value: 11, Comment: 
	@CrossCountrySkiing = 0x0C, // Value: 12, Comment: 
	@AlpineSkiing = 0x0D, // Value: 13, Comment: 
	@Snowboarding = 0x0E, // Value: 14, Comment: 
	@Rowing = 0x0F, // Value: 15, Comment: 
	@Mountaineering = 0x10, // Value: 16, Comment: 
	@Hiking = 0x11, // Value: 17, Comment: 
	@Multisport = 0x12, // Value: 18, Comment: 
	@Paddling = 0x13, // Value: 19, Comment: 
	@Flying = 0x14, // Value: 20, Comment: 
	@EBiking = 0x15, // Value: 21, Comment: 
	@Motorcycling = 0x16, // Value: 22, Comment: 
	@Boating = 0x17, // Value: 23, Comment: 
	@Driving = 0x18, // Value: 24, Comment: 
	@Golf = 0x19, // Value: 25, Comment: 
	@HangGliding = 0x1A, // Value: 26, Comment: 
	@HorsebackRiding = 0x1B, // Value: 27, Comment: 
	@Hunting = 0x1C, // Value: 28, Comment: 
	@Fishing = 0x1D, // Value: 29, Comment: 
	@InlineSkating = 0x1E, // Value: 30, Comment: 
	@RockClimbing = 0x1F, // Value: 31, Comment: 
	@Sailing = 0x20, // Value: 32, Comment: 
	@IceSkating = 0x21, // Value: 33, Comment: 
	@SkyDiving = 0x22, // Value: 34, Comment: 
	@Snowshoeing = 0x23, // Value: 35, Comment: 
	@Snowmobiling = 0x24, // Value: 36, Comment: 
	@StandUpPaddleboarding = 0x25, // Value: 37, Comment: 
	@Surfing = 0x26, // Value: 38, Comment: 
	@Wakeboarding = 0x27, // Value: 39, Comment: 
	@WaterSkiing = 0x28, // Value: 40, Comment: 
	@Kayaking = 0x29, // Value: 41, Comment: 
	@Rafting = 0x2A, // Value: 42, Comment: 
	@Windsurfing = 0x2B, // Value: 43, Comment: 
	@Kitesurfing = 0x2C, // Value: 44, Comment: 
	@Tactical = 0x2D, // Value: 45, Comment: 
	@Jumpmaster = 0x2E, // Value: 46, Comment: 
	@Boxing = 0x2F, // Value: 47, Comment: 
	@FloorClimbing = 0x30, // Value: 48, Comment: 
	@Baseball = 0x31, // Value: 49, Comment: 
	@Diving = 0x35, // Value: 53, Comment: 
	@Hiit = 0x3E, // Value: 62, Comment: 
	@Racket = 0x40, // Value: 64, Comment: 
	@WheelchairPushWalk = 0x41, // Value: 65, Comment: 
	@WheelchairPushRun = 0x42, // Value: 66, Comment: 
	@Meditation = 0x43, // Value: 67, Comment: 
	@DiscGolf = 0x45, // Value: 69, Comment: 
	@Cricket = 0x47, // Value: 71, Comment: 
	@Rugby = 0x48, // Value: 72, Comment: 
	@Hockey = 0x49, // Value: 73, Comment: 
	@Lacrosse = 0x4A, // Value: 74, Comment: 
	@Volleyball = 0x4B, // Value: 75, Comment: 
	@WaterTubing = 0x4C, // Value: 76, Comment: 
	@Wakesurfing = 0x4D, // Value: 77, Comment: 
	@MixedMartialArts = 0x50, // Value: 80, Comment: 
	@Snorkeling = 0x52, // Value: 82, Comment: 
	@Dance = 0x53, // Value: 83, Comment: 
	@JumpRope = 0x54, // Value: 84, Comment: 
	@All = 0xFE // Value: 254, Comment: 
};
