#include "fitTypeDecls.idl"

enum<uint16,0xFFFF> ShoulderPressExerciseName
{
	@AlternatingDumbbellShoulderPress = 0x0000, // Value: 0, Comment: 
	@ArnoldPress = 0x0001, // Value: 1, Comment: 
	@BarbellFrontSquatToPushPress = 0x0002, // Value: 2, Comment: 
	@BarbellPushPress = 0x0003, // Value: 3, Comment: 
	@BarbellShoulderPress = 0x0004, // Value: 4, Comment: 
	@DeadCurlPress = 0x0005, // Value: 5, Comment: 
	@DumbbellAlternatingShoulderPressAndTwist = 0x0006, // Value: 6, Comment: 
	@DumbbellHammerCurlToLungeToPress = 0x0007, // Value: 7, Comment: 
	@DumbbellPushPress = 0x0008, // Value: 8, Comment: 
	@FloorInvertedShoulderPress = 0x0009, // Value: 9, Comment: 
	@WeightedFloorInvertedShoulderPress = 0x000A, // Value: 10, Comment: 
	@InvertedShoulderPress = 0x000B, // Value: 11, Comment: 
	@WeightedInvertedShoulderPress = 0x000C, // Value: 12, Comment: 
	@OneArmPushPress = 0x000D, // Value: 13, Comment: 
	@OverheadBarbellPress = 0x000E, // Value: 14, Comment: 
	@OverheadDumbbellPress = 0x000F, // Value: 15, Comment: 
	@SeatedBarbellShoulderPress = 0x0010, // Value: 16, Comment: 
	@SeatedDumbbellShoulderPress = 0x0011, // Value: 17, Comment: 
	@SingleArmDumbbellShoulderPress = 0x0012, // Value: 18, Comment: 
	@SingleArmStepUpAndPress = 0x0013, // Value: 19, Comment: 
	@SmithMachineOverheadPress = 0x0014, // Value: 20, Comment: 
	@SplitStanceHammerCurlToPress = 0x0015, // Value: 21, Comment: 
	@SwissBallDumbbellShoulderPress = 0x0016, // Value: 22, Comment: 
	@WeightPlateFrontRaise = 0x0017 // Value: 23, Comment: 
};
