#include "fitTypeDecls.idl"

enum<byte,0xFF> SleepLevel
{
	@Unmeasurable = 0x00, // Value: 0, Comment: 
	@Awake = 0x01, // Value: 1, Comment: 
	@Light = 0x02, // Value: 2, Comment: 
	@Deep = 0x03, // Value: 3, Comment: 
	@Rem = 0x04 // Value: 4, Comment: 
};
