#include "fitTypeDecls.idl"

enum<byte,0xFF> TimeZone
{
	@Almaty = 0x00, // Value: 0, Comment: 
	@Bangkok = 0x01, // Value: 1, Comment: 
	@Bombay = 0x02, // Value: 2, Comment: 
	@Brasilia = 0x03, // Value: 3, Comment: 
	@Cairo = 0x04, // Value: 4, Comment: 
	@CapeVerdeIs = 0x05, // Value: 5, Comment: 
	@Darwin = 0x06, // Value: 6, Comment: 
	@Eniwetok = 0x07, // Value: 7, Comment: 
	@Fiji = 0x08, // Value: 8, Comment: 
	@HongKong = 0x09, // Value: 9, Comment: 
	@Islamabad = 0x0A, // Value: 10, Comment: 
	@Kabul = 0x0B, // Value: 11, Comment: 
	@Magadan = 0x0C, // Value: 12, Comment: 
	@MidAtlantic = 0x0D, // Value: 13, Comment: 
	@Moscow = 0x0E, // Value: 14, Comment: 
	@Muscat = 0x0F, // Value: 15, Comment: 
	@Newfoundland = 0x10, // Value: 16, Comment: 
	@Samoa = 0x11, // Value: 17, Comment: 
	@Sydney = 0x12, // Value: 18, Comment: 
	@Tehran = 0x13, // Value: 19, Comment: 
	@Tokyo = 0x14, // Value: 20, Comment: 
	@UsAlaska = 0x15, // Value: 21, Comment: 
	@UsAtlantic = 0x16, // Value: 22, Comment: 
	@UsCentral = 0x17, // Value: 23, Comment: 
	@UsEastern = 0x18, // Value: 24, Comment: 
	@UsHawaii = 0x19, // Value: 25, Comment: 
	@UsMountain = 0x1A, // Value: 26, Comment: 
	@UsPacific = 0x1B, // Value: 27, Comment: 
	@Other = 0x1C, // Value: 28, Comment: 
	@Auckland = 0x1D, // Value: 29, Comment: 
	@Kathmandu = 0x1E, // Value: 30, Comment: 
	@EuropeWesternWet = 0x1F, // Value: 31, Comment: 
	@EuropeCentralCet = 0x20, // Value: 32, Comment: 
	@EuropeEasternEet = 0x21, // Value: 33, Comment: 
	@Jakarta = 0x22, // Value: 34, Comment: 
	@Perth = 0x23, // Value: 35, Comment: 
	@Adelaide = 0x24, // Value: 36, Comment: 
	@Brisbane = 0x25, // Value: 37, Comment: 
	@Tasmania = 0x26, // Value: 38, Comment: 
	@Iceland = 0x27, // Value: 39, Comment: 
	@Amsterdam = 0x28, // Value: 40, Comment: 
	@Athens = 0x29, // Value: 41, Comment: 
	@Barcelona = 0x2A, // Value: 42, Comment: 
	@Berlin = 0x2B, // Value: 43, Comment: 
	@Brussels = 0x2C, // Value: 44, Comment: 
	@Budapest = 0x2D, // Value: 45, Comment: 
	@Copenhagen = 0x2E, // Value: 46, Comment: 
	@Dublin = 0x2F, // Value: 47, Comment: 
	@Helsinki = 0x30, // Value: 48, Comment: 
	@Lisbon = 0x31, // Value: 49, Comment: 
	@London = 0x32, // Value: 50, Comment: 
	@Madrid = 0x33, // Value: 51, Comment: 
	@Munich = 0x34, // Value: 52, Comment: 
	@Oslo = 0x35, // Value: 53, Comment: 
	@Paris = 0x36, // Value: 54, Comment: 
	@Prague = 0x37, // Value: 55, Comment: 
	@Reykjavik = 0x38, // Value: 56, Comment: 
	@Rome = 0x39, // Value: 57, Comment: 
	@Stockholm = 0x3A, // Value: 58, Comment: 
	@Vienna = 0x3B, // Value: 59, Comment: 
	@Warsaw = 0x3C, // Value: 60, Comment: 
	@Zurich = 0x3D, // Value: 61, Comment: 
	@Quebec = 0x3E, // Value: 62, Comment: 
	@Ontario = 0x3F, // Value: 63, Comment: 
	@Manitoba = 0x40, // Value: 64, Comment: 
	@Saskatchewan = 0x41, // Value: 65, Comment: 
	@Alberta = 0x42, // Value: 66, Comment: 
	@BritishColumbia = 0x43, // Value: 67, Comment: 
	@Boise = 0x44, // Value: 68, Comment: 
	@Boston = 0x45, // Value: 69, Comment: 
	@Chicago = 0x46, // Value: 70, Comment: 
	@Dallas = 0x47, // Value: 71, Comment: 
	@Denver = 0x48, // Value: 72, Comment: 
	@KansasCity = 0x49, // Value: 73, Comment: 
	@LasVegas = 0x4A, // Value: 74, Comment: 
	@LosAngeles = 0x4B, // Value: 75, Comment: 
	@Miami = 0x4C, // Value: 76, Comment: 
	@Minneapolis = 0x4D, // Value: 77, Comment: 
	@NewYork = 0x4E, // Value: 78, Comment: 
	@NewOrleans = 0x4F, // Value: 79, Comment: 
	@Phoenix = 0x50, // Value: 80, Comment: 
	@SantaFe = 0x51, // Value: 81, Comment: 
	@Seattle = 0x52, // Value: 82, Comment: 
	@WashingtonDc = 0x53, // Value: 83, Comment: 
	@UsArizona = 0x54, // Value: 84, Comment: 
	@Chita = 0x55, // Value: 85, Comment: 
	@Ekaterinburg = 0x56, // Value: 86, Comment: 
	@Irkutsk = 0x57, // Value: 87, Comment: 
	@Kaliningrad = 0x58, // Value: 88, Comment: 
	@Krasnoyarsk = 0x59, // Value: 89, Comment: 
	@Novosibirsk = 0x5A, // Value: 90, Comment: 
	@PetropavlovskKamchatskiy = 0x5B, // Value: 91, Comment: 
	@Samara = 0x5C, // Value: 92, Comment: 
	@Vladivostok = 0x5D, // Value: 93, Comment: 
	@MexicoCentral = 0x5E, // Value: 94, Comment: 
	@MexicoMountain = 0x5F, // Value: 95, Comment: 
	@MexicoPacific = 0x60, // Value: 96, Comment: 
	@CapeTown = 0x61, // Value: 97, Comment: 
	@Winkhoek = 0x62, // Value: 98, Comment: 
	@Lagos = 0x63, // Value: 99, Comment: 
	@Riyahd = 0x64, // Value: 100, Comment: 
	@Venezuela = 0x65, // Value: 101, Comment: 
	@AustraliaLh = 0x66, // Value: 102, Comment: 
	@Santiago = 0x67, // Value: 103, Comment: 
	@Manual = 0xFD, // Value: 253, Comment: 
	@Automatic = 0xFE // Value: 254, Comment: 
};
