#include "fitTypeDecls.idl"

enum<byte,0xFF> WeatherSevereType
{
	@Unspecified = 0x00, // Value: 0, Comment: 
	@Tornado = 0x01, // Value: 1, Comment: 
	@Tsunami = 0x02, // Value: 2, Comment: 
	@Hurricane = 0x03, // Value: 3, Comment: 
	@ExtremeWind = 0x04, // Value: 4, Comment: 
	@Typhoon = 0x05, // Value: 5, Comment: 
	@InlandHurricane = 0x06, // Value: 6, Comment: 
	@HurricaneForceWind = 0x07, // Value: 7, Comment: 
	@Waterspout = 0x08, // Value: 8, Comment: 
	@SevereThunderstorm = 0x09, // Value: 9, Comment: 
	@WreckhouseWinds = 0x0A, // Value: 10, Comment: 
	@LesSuetesWind = 0x0B, // Value: 11, Comment: 
	@Avalanche = 0x0C, // Value: 12, Comment: 
	@FlashFlood = 0x0D, // Value: 13, Comment: 
	@TropicalStorm = 0x0E, // Value: 14, Comment: 
	@InlandTropicalStorm = 0x0F, // Value: 15, Comment: 
	@Blizzard = 0x10, // Value: 16, Comment: 
	@IceStorm = 0x11, // Value: 17, Comment: 
	@FreezingRain = 0x12, // Value: 18, Comment: 
	@DebrisFlow = 0x13, // Value: 19, Comment: 
	@FlashFreeze = 0x14, // Value: 20, Comment: 
	@DustStorm = 0x15, // Value: 21, Comment: 
	@HighWind = 0x16, // Value: 22, Comment: 
	@WinterStorm = 0x17, // Value: 23, Comment: 
	@HeavyFreezingSpray = 0x18, // Value: 24, Comment: 
	@ExtremeCold = 0x19, // Value: 25, Comment: 
	@WindChill = 0x1A, // Value: 26, Comment: 
	@ColdWave = 0x1B, // Value: 27, Comment: 
	@HeavySnowAlert = 0x1C, // Value: 28, Comment: 
	@LakeEffectBlowingSnow = 0x1D, // Value: 29, Comment: 
	@SnowSquall = 0x1E, // Value: 30, Comment: 
	@LakeEffectSnow = 0x1F, // Value: 31, Comment: 
	@WinterWeather = 0x20, // Value: 32, Comment: 
	@Sleet = 0x21, // Value: 33, Comment: 
	@Snowfall = 0x22, // Value: 34, Comment: 
	@SnowAndBlowingSnow = 0x23, // Value: 35, Comment: 
	@BlowingSnow = 0x24, // Value: 36, Comment: 
	@SnowAlert = 0x25, // Value: 37, Comment: 
	@ArcticOutflow = 0x26, // Value: 38, Comment: 
	@FreezingDrizzle = 0x27, // Value: 39, Comment: 
	@Storm = 0x28, // Value: 40, Comment: 
	@StormSurge = 0x29, // Value: 41, Comment: 
	@Rainfall = 0x2A, // Value: 42, Comment: 
	@ArealFlood = 0x2B, // Value: 43, Comment: 
	@CoastalFlood = 0x2C, // Value: 44, Comment: 
	@LakeshoreFlood = 0x2D, // Value: 45, Comment: 
	@ExcessiveHeat = 0x2E, // Value: 46, Comment: 
	@Heat = 0x2F, // Value: 47, Comment: 
	@Weather = 0x30, // Value: 48, Comment: 
	@HighHeatAndHumidity = 0x31, // Value: 49, Comment: 
	@HumidexAndHealth = 0x32, // Value: 50, Comment: 
	@Humidex = 0x33, // Value: 51, Comment: 
	@Gale = 0x34, // Value: 52, Comment: 
	@FreezingSpray = 0x35, // Value: 53, Comment: 
	@SpecialMarine = 0x36, // Value: 54, Comment: 
	@Squall = 0x37, // Value: 55, Comment: 
	@StrongWind = 0x38, // Value: 56, Comment: 
	@LakeWind = 0x39, // Value: 57, Comment: 
	@MarineWeather = 0x3A, // Value: 58, Comment: 
	@Wind = 0x3B, // Value: 59, Comment: 
	@SmallCraftHazardousSeas = 0x3C, // Value: 60, Comment: 
	@HazardousSeas = 0x3D, // Value: 61, Comment: 
	@SmallCraft = 0x3E, // Value: 62, Comment: 
	@SmallCraftWinds = 0x3F, // Value: 63, Comment: 
	@SmallCraftRoughBar = 0x40, // Value: 64, Comment: 
	@HighWaterLevel = 0x41, // Value: 65, Comment: 
	@Ashfall = 0x42, // Value: 66, Comment: 
	@FreezingFog = 0x43, // Value: 67, Comment: 
	@DenseFog = 0x44, // Value: 68, Comment: 
	@DenseSmoke = 0x45, // Value: 69, Comment: 
	@BlowingDust = 0x46, // Value: 70, Comment: 
	@HardFreeze = 0x47, // Value: 71, Comment: 
	@Freeze = 0x48, // Value: 72, Comment: 
	@Frost = 0x49, // Value: 73, Comment: 
	@FireWeather = 0x4A, // Value: 74, Comment: 
	@Flood = 0x4B, // Value: 75, Comment: 
	@RipTide = 0x4C, // Value: 76, Comment: 
	@HighSurf = 0x4D, // Value: 77, Comment: 
	@Smog = 0x4E, // Value: 78, Comment: 
	@AirQuality = 0x4F, // Value: 79, Comment: 
	@BriskWind = 0x50, // Value: 80, Comment: 
	@AirStagnation = 0x51, // Value: 81, Comment: 
	@LowWater = 0x52, // Value: 82, Comment: 
	@Hydrological = 0x53, // Value: 83, Comment: 
	@SpecialWeather = 0x54 // Value: 84, Comment: 
};
