#include "fitTypeDecls.idl"

enum<uint16,0xFFFF> WarmUpExerciseName
{
	@QuadrupedRocking = 0x0000, // Value: 0, Comment: 
	@NeckTilts = 0x0001, // Value: 1, Comment: 
	@AnkleCircles = 0x0002, // Value: 2, Comment: 
	@AnkleDorsiflexionWithBand = 0x0003, // Value: 3, Comment: 
	@AnkleInternalRotation = 0x0004, // Value: 4, Comment: 
	@ArmCircles = 0x0005, // Value: 5, Comment: 
	@BentOverReachToSky = 0x0006, // Value: 6, Comment: 
	@CatCamel = 0x0007, // Value: 7, Comment: 
	@ElbowToFootLunge = 0x0008, // Value: 8, Comment: 
	@ForwardAndBackwardLegSwings = 0x0009, // Value: 9, Comment: 
	@Groiners = 0x000A, // Value: 10, Comment: 
	@InvertedHamstringStretch = 0x000B, // Value: 11, Comment: 
	@LateralDuckUnder = 0x000C, // Value: 12, Comment: 
	@NeckRotations = 0x000D, // Value: 13, Comment: 
	@OppositeArmAndLegBalance = 0x000E, // Value: 14, Comment: 
	@ReachRollAndLift = 0x000F, // Value: 15, Comment: 
	@ShoulderCircles = 0x0011, // Value: 17, Comment: 
	@SideToSideLegSwings = 0x0012, // Value: 18, Comment: 
	@SleeperStretch = 0x0013, // Value: 19, Comment: 
	@SlideOut = 0x0014, // Value: 20, Comment: 
	@SwissBallHipCrossover = 0x0015, // Value: 21, Comment: 
	@SwissBallReachRollAndLift = 0x0016, // Value: 22, Comment: 
	@SwissBallWindshieldWipers = 0x0017, // Value: 23, Comment: 
	@ThoracicRotation = 0x0018, // Value: 24, Comment: 
	@WalkingHighKicks = 0x0019, // Value: 25, Comment: 
	@WalkingHighKnees = 0x001A, // Value: 26, Comment: 
	@WalkingKneeHugs = 0x001B, // Value: 27, Comment: 
	@WalkingLegCradles = 0x001C, // Value: 28, Comment: 
	@Walkout = 0x001D, // Value: 29, Comment: 
	@WalkoutFromPushUpPosition = 0x001E // Value: 30, Comment: 
};
